// Code generated by MockGen. DO NOT EDIT.
// Source: i_password_proof_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_password_proof_proxy.go -destination=mocks/mock_i_password_proof_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPasswordProofProxy is a mock of IPasswordProofProxy interface.
type MockIPasswordProofProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIPasswordProofProxyMockRecorder
	isgomock struct{}
}

// MockIPasswordProofProxyMockRecorder is the mock recorder for MockIPasswordProofProxy.
type MockIPasswordProofProxyMockRecorder struct {
	mock *MockIPasswordProofProxy
}

// NewMockIPasswordProofProxy creates a new mock instance.
func NewMockIPasswordProofProxy(ctrl *gomock.Controller) *MockIPasswordProofProxy {
	mock := &MockIPasswordProofProxy{ctrl: ctrl}
	mock.recorder = &MockIPasswordProofProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPasswordProofProxy) EXPECT() *MockIPasswordProofProxyMockRecorder {
	return m.recorder
}

// DecoyProof mocks base method.
func (m *MockIPasswordProofProxy) DecoyProof() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecoyProof")
	ret0, _ := ret[0].(string)
	return ret0
}

// DecoyProof indicates an expected call of DecoyProof.
func (mr *MockIPasswordProofProxyMockRecorder) DecoyProof() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecoyProof", reflect.TypeOf((*MockIPasswordProofProxy)(nil).DecoyProof))
}

// Matches mocks base method.
func (m *MockIPasswordProofProxy) Matches(password, passwordProof string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Matches", password, passwordProof)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Matches indicates an expected call of Matches.
func (mr *MockIPasswordProofProxyMockRecorder) Matches(password, passwordProof any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Matches", reflect.TypeOf((*MockIPasswordProofProxy)(nil).Matches), password, passwordProof)
}

// Prove mocks base method.
func (m *MockIPasswordProofProxy) Prove(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prove", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prove indicates an expected call of Prove.
func (mr *MockIPasswordProofProxyMockRecorder) Prove(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prove", reflect.TypeOf((*MockIPasswordProofProxy)(nil).Prove), password)
}
