// Code generated by MockGen. DO NOT EDIT.
// Source: i_binance_trading_key_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_binance_trading_key_repository.go -destination=mocks/mock_i_binance_trading_key_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIBinanceTradingKeyRepository is a mock of IBinanceTradingKeyRepository interface.
type MockIBinanceTradingKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIBinanceTradingKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockIBinanceTradingKeyRepositoryMockRecorder is the mock recorder for MockIBinanceTradingKeyRepository.
type MockIBinanceTradingKeyRepositoryMockRecorder struct {
	mock *MockIBinanceTradingKeyRepository
}

// NewMockIBinanceTradingKeyRepository creates a new mock instance.
func NewMockIBinanceTradingKeyRepository(ctrl *gomock.Controller) *MockIBinanceTradingKeyRepository {
	mock := &MockIBinanceTradingKeyRepository{ctrl: ctrl}
	mock.recorder = &MockIBinanceTradingKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBinanceTradingKeyRepository) EXPECT() *MockIBinanceTradingKeyRepositoryMockRecorder {
	return m.recorder
}

// DeleteByUser mocks base method.
func (m *MockIBinanceTradingKeyRepository) DeleteByUser(executionContext context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", executionContext, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockIBinanceTradingKeyRepositoryMockRecorder) DeleteByUser(executionContext, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockIBinanceTradingKeyRepository)(nil).DeleteByUser), executionContext, userID)
}

// FindOneByUser mocks base method.
func (m *MockIBinanceTradingKeyRepository) FindOneByUser(executionContext context.Context, userID uint) (entities.BinanceTradingKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUser", executionContext, userID)
	ret0, _ := ret[0].(entities.BinanceTradingKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUser indicates an expected call of FindOneByUser.
func (mr *MockIBinanceTradingKeyRepositoryMockRecorder) FindOneByUser(executionContext, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUser", reflect.TypeOf((*MockIBinanceTradingKeyRepository)(nil).FindOneByUser), executionContext, userID)
}

// Replace mocks base method.
func (m *MockIBinanceTradingKeyRepository) Replace(executionContext context.Context, binanceTradingKey entities.BinanceTradingKey, uncoveredBotMarketDataKinds []string) (entities.BinanceTradingKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", executionContext, binanceTradingKey, uncoveredBotMarketDataKinds)
	ret0, _ := ret[0].(entities.BinanceTradingKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockIBinanceTradingKeyRepositoryMockRecorder) Replace(executionContext, binanceTradingKey, uncoveredBotMarketDataKinds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockIBinanceTradingKeyRepository)(nil).Replace), executionContext, binanceTradingKey, uncoveredBotMarketDataKinds)
}
