// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_trading_symbol_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_trading_symbol_repository.go -destination=mocks/mock_i_contract_trading_symbol_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractTradingSymbolRepository is a mock of IContractTradingSymbolRepository interface.
type MockIContractTradingSymbolRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContractTradingSymbolRepositoryMockRecorder
	isgomock struct{}
}

// MockIContractTradingSymbolRepositoryMockRecorder is the mock recorder for MockIContractTradingSymbolRepository.
type MockIContractTradingSymbolRepositoryMockRecorder struct {
	mock *MockIContractTradingSymbolRepository
}

// NewMockIContractTradingSymbolRepository creates a new mock instance.
func NewMockIContractTradingSymbolRepository(ctrl *gomock.Controller) *MockIContractTradingSymbolRepository {
	mock := &MockIContractTradingSymbolRepository{ctrl: ctrl}
	mock.recorder = &MockIContractTradingSymbolRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractTradingSymbolRepository) EXPECT() *MockIContractTradingSymbolRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockIContractTradingSymbolRepository) FindAll(executionContext context.Context) ([]entities.ContractTradingSymbol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", executionContext)
	ret0, _ := ret[0].([]entities.ContractTradingSymbol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIContractTradingSymbolRepositoryMockRecorder) FindAll(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIContractTradingSymbolRepository)(nil).FindAll), executionContext)
}

// FindBySymbol mocks base method.
func (m *MockIContractTradingSymbolRepository) FindBySymbol(executionContext context.Context, symbol string) (entities.ContractTradingSymbol, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySymbol", executionContext, symbol)
	ret0, _ := ret[0].(entities.ContractTradingSymbol)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindBySymbol indicates an expected call of FindBySymbol.
func (mr *MockIContractTradingSymbolRepositoryMockRecorder) FindBySymbol(executionContext, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySymbol", reflect.TypeOf((*MockIContractTradingSymbolRepository)(nil).FindBySymbol), executionContext, symbol)
}

// FindWatched mocks base method.
func (m *MockIContractTradingSymbolRepository) FindWatched(executionContext context.Context) ([]entities.ContractTradingSymbol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWatched", executionContext)
	ret0, _ := ret[0].([]entities.ContractTradingSymbol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWatched indicates an expected call of FindWatched.
func (mr *MockIContractTradingSymbolRepositoryMockRecorder) FindWatched(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWatched", reflect.TypeOf((*MockIContractTradingSymbolRepository)(nil).FindWatched), executionContext)
}

// Save mocks base method.
func (m *MockIContractTradingSymbolRepository) Save(executionContext context.Context, contractTradingSymbol entities.ContractTradingSymbol) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, contractTradingSymbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIContractTradingSymbolRepositoryMockRecorder) Save(executionContext, contractTradingSymbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIContractTradingSymbolRepository)(nil).Save), executionContext, contractTradingSymbol)
}
