// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_position_statistic_archive_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_position_statistic_archive_proxy.go -destination=mocks/mock_i_contract_position_statistic_archive_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractPositionStatisticArchiveProxy is a mock of IContractPositionStatisticArchiveProxy interface.
type MockIContractPositionStatisticArchiveProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIContractPositionStatisticArchiveProxyMockRecorder
	isgomock struct{}
}

// MockIContractPositionStatisticArchiveProxyMockRecorder is the mock recorder for MockIContractPositionStatisticArchiveProxy.
type MockIContractPositionStatisticArchiveProxyMockRecorder struct {
	mock *MockIContractPositionStatisticArchiveProxy
}

// NewMockIContractPositionStatisticArchiveProxy creates a new mock instance.
func NewMockIContractPositionStatisticArchiveProxy(ctrl *gomock.Controller) *MockIContractPositionStatisticArchiveProxy {
	mock := &MockIContractPositionStatisticArchiveProxy{ctrl: ctrl}
	mock.recorder = &MockIContractPositionStatisticArchiveProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractPositionStatisticArchiveProxy) EXPECT() *MockIContractPositionStatisticArchiveProxyMockRecorder {
	return m.recorder
}

// FetchDailyPositionStatistics mocks base method.
func (m *MockIContractPositionStatisticArchiveProxy) FetchDailyPositionStatistics(executionContext context.Context, symbol string, day time.Time) ([]vo.ContractPositionStatisticArchiveVo, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDailyPositionStatistics", executionContext, symbol, day)
	ret0, _ := ret[0].([]vo.ContractPositionStatisticArchiveVo)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchDailyPositionStatistics indicates an expected call of FetchDailyPositionStatistics.
func (mr *MockIContractPositionStatisticArchiveProxyMockRecorder) FetchDailyPositionStatistics(executionContext, symbol, day any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDailyPositionStatistics", reflect.TypeOf((*MockIContractPositionStatisticArchiveProxy)(nil).FetchDailyPositionStatistics), executionContext, symbol, day)
}
