// Code generated by MockGen. DO NOT EDIT.
// Source: i_strategy_bot_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_strategy_bot_repository.go -destination=mocks/mock_i_strategy_bot_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIStrategyBotRepository is a mock of IStrategyBotRepository interface.
type MockIStrategyBotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyBotRepositoryMockRecorder
	isgomock struct{}
}

// MockIStrategyBotRepositoryMockRecorder is the mock recorder for MockIStrategyBotRepository.
type MockIStrategyBotRepositoryMockRecorder struct {
	mock *MockIStrategyBotRepository
}

// NewMockIStrategyBotRepository creates a new mock instance.
func NewMockIStrategyBotRepository(ctrl *gomock.Controller) *MockIStrategyBotRepository {
	mock := &MockIStrategyBotRepository{ctrl: ctrl}
	mock.recorder = &MockIStrategyBotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategyBotRepository) EXPECT() *MockIStrategyBotRepositoryMockRecorder {
	return m.recorder
}

// CountRunningByOwner mocks base method.
func (m *MockIStrategyBotRepository) CountRunningByOwner(executionContext context.Context, ownerID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRunningByOwner", executionContext, ownerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRunningByOwner indicates an expected call of CountRunningByOwner.
func (mr *MockIStrategyBotRepositoryMockRecorder) CountRunningByOwner(executionContext, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRunningByOwner", reflect.TypeOf((*MockIStrategyBotRepository)(nil).CountRunningByOwner), executionContext, ownerID)
}

// Delete mocks base method.
func (m *MockIStrategyBotRepository) Delete(executionContext context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", executionContext, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIStrategyBotRepositoryMockRecorder) Delete(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIStrategyBotRepository)(nil).Delete), executionContext, id)
}

// FindAllByOwner mocks base method.
func (m *MockIStrategyBotRepository) FindAllByOwner(executionContext context.Context, ownerID uint) ([]entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByOwner", executionContext, ownerID)
	ret0, _ := ret[0].([]entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByOwner indicates an expected call of FindAllByOwner.
func (mr *MockIStrategyBotRepositoryMockRecorder) FindAllByOwner(executionContext, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByOwner", reflect.TypeOf((*MockIStrategyBotRepository)(nil).FindAllByOwner), executionContext, ownerID)
}

// FindDue mocks base method.
func (m *MockIStrategyBotRepository) FindDue(executionContext context.Context, moment time.Time, limit int) ([]entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDue", executionContext, moment, limit)
	ret0, _ := ret[0].([]entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDue indicates an expected call of FindDue.
func (mr *MockIStrategyBotRepositoryMockRecorder) FindDue(executionContext, moment, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDue", reflect.TypeOf((*MockIStrategyBotRepository)(nil).FindDue), executionContext, moment, limit)
}

// FindOne mocks base method.
func (m *MockIStrategyBotRepository) FindOne(executionContext context.Context, id uint) (entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIStrategyBotRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIStrategyBotRepository)(nil).FindOne), executionContext, id)
}

// Save mocks base method.
func (m *MockIStrategyBotRepository) Save(executionContext context.Context, bot entities.StrategyBot) (entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, bot)
	ret0, _ := ret[0].(entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIStrategyBotRepositoryMockRecorder) Save(executionContext, bot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIStrategyBotRepository)(nil).Save), executionContext, bot)
}

// UpdateRunState mocks base method.
func (m *MockIStrategyBotRepository) UpdateRunState(executionContext context.Context, bot entities.StrategyBot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunState", executionContext, bot)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunState indicates an expected call of UpdateRunState.
func (mr *MockIStrategyBotRepositoryMockRecorder) UpdateRunState(executionContext, bot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunState", reflect.TypeOf((*MockIStrategyBotRepository)(nil).UpdateRunState), executionContext, bot)
}
