// Code generated by MockGen. DO NOT EDIT.
// Source: i_access_token_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_access_token_proxy.go -destination=mocks/mock_i_access_token_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIAccessTokenProxy is a mock of IAccessTokenProxy interface.
type MockIAccessTokenProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIAccessTokenProxyMockRecorder
	isgomock struct{}
}

// MockIAccessTokenProxyMockRecorder is the mock recorder for MockIAccessTokenProxy.
type MockIAccessTokenProxyMockRecorder struct {
	mock *MockIAccessTokenProxy
}

// NewMockIAccessTokenProxy creates a new mock instance.
func NewMockIAccessTokenProxy(ctrl *gomock.Controller) *MockIAccessTokenProxy {
	mock := &MockIAccessTokenProxy{ctrl: ctrl}
	mock.recorder = &MockIAccessTokenProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccessTokenProxy) EXPECT() *MockIAccessTokenProxyMockRecorder {
	return m.recorder
}

// ClaimsOf mocks base method.
func (m *MockIAccessTokenProxy) ClaimsOf(accessToken string) (vo.AccessTokenClaimsVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimsOf", accessToken)
	ret0, _ := ret[0].(vo.AccessTokenClaimsVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimsOf indicates an expected call of ClaimsOf.
func (mr *MockIAccessTokenProxyMockRecorder) ClaimsOf(accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimsOf", reflect.TypeOf((*MockIAccessTokenProxy)(nil).ClaimsOf), accessToken)
}

// Issue mocks base method.
func (m *MockIAccessTokenProxy) Issue(claims vo.AccessTokenClaimsVo) (vo.AccessTokenVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", claims)
	ret0, _ := ret[0].(vo.AccessTokenVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockIAccessTokenProxyMockRecorder) Issue(claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockIAccessTokenProxy)(nil).Issue), claims)
}

// UserIdentifiedBy mocks base method.
func (m *MockIAccessTokenProxy) UserIdentifiedBy(accessToken string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIdentifiedBy", accessToken)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIdentifiedBy indicates an expected call of UserIdentifiedBy.
func (mr *MockIAccessTokenProxyMockRecorder) UserIdentifiedBy(accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIdentifiedBy", reflect.TypeOf((*MockIAccessTokenProxy)(nil).UserIdentifiedBy), accessToken)
}
