// Code generated by MockGen. DO NOT EDIT.
// Source: i_assistant_query.go
//
// Generated by this command:
//
//	mockgen -source=i_assistant_query.go -destination=mocks/mock_i_assistant_query.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAssistantQuery is a mock of IAssistantQuery interface.
type MockIAssistantQuery struct {
	ctrl     *gomock.Controller
	recorder *MockIAssistantQueryMockRecorder
	isgomock struct{}
}

// MockIAssistantQueryMockRecorder is the mock recorder for MockIAssistantQuery.
type MockIAssistantQueryMockRecorder struct {
	mock *MockIAssistantQuery
}

// NewMockIAssistantQuery creates a new mock instance.
func NewMockIAssistantQuery(ctrl *gomock.Controller) *MockIAssistantQuery {
	mock := &MockIAssistantQuery{ctrl: ctrl}
	mock.recorder = &MockIAssistantQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssistantQuery) EXPECT() *MockIAssistantQueryMockRecorder {
	return m.recorder
}

// ArgumentSchema mocks base method.
func (m *MockIAssistantQuery) ArgumentSchema() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArgumentSchema")
	ret0, _ := ret[0].(string)
	return ret0
}

// ArgumentSchema indicates an expected call of ArgumentSchema.
func (mr *MockIAssistantQueryMockRecorder) ArgumentSchema() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArgumentSchema", reflect.TypeOf((*MockIAssistantQuery)(nil).ArgumentSchema))
}

// Description mocks base method.
func (m *MockIAssistantQuery) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockIAssistantQueryMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockIAssistantQuery)(nil).Description))
}

// Name mocks base method.
func (m *MockIAssistantQuery) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockIAssistantQueryMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockIAssistantQuery)(nil).Name))
}

// Run mocks base method.
func (m *MockIAssistantQuery) Run(executionContext context.Context, arguments string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", executionContext, arguments)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockIAssistantQueryMockRecorder) Run(executionContext, arguments any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIAssistantQuery)(nil).Run), executionContext, arguments)
}
