// Code generated by MockGen. DO NOT EDIT.
// Source: i_trade_tag_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_trade_tag_repository.go -destination=mocks/mock_i_trade_tag_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockITradeTagRepository is a mock of ITradeTagRepository interface.
type MockITradeTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITradeTagRepositoryMockRecorder
	isgomock struct{}
}

// MockITradeTagRepositoryMockRecorder is the mock recorder for MockITradeTagRepository.
type MockITradeTagRepositoryMockRecorder struct {
	mock *MockITradeTagRepository
}

// NewMockITradeTagRepository creates a new mock instance.
func NewMockITradeTagRepository(ctrl *gomock.Controller) *MockITradeTagRepository {
	mock := &MockITradeTagRepository{ctrl: ctrl}
	mock.recorder = &MockITradeTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITradeTagRepository) EXPECT() *MockITradeTagRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockITradeTagRepository) Create(executionContext context.Context, tag entities.TradeTag) (entities.TradeTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", executionContext, tag)
	ret0, _ := ret[0].(entities.TradeTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockITradeTagRepositoryMockRecorder) Create(executionContext, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockITradeTagRepository)(nil).Create), executionContext, tag)
}

// CreateIfAbsent mocks base method.
func (m *MockITradeTagRepository) CreateIfAbsent(executionContext context.Context, tags []entities.TradeTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIfAbsent", executionContext, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIfAbsent indicates an expected call of CreateIfAbsent.
func (mr *MockITradeTagRepositoryMockRecorder) CreateIfAbsent(executionContext, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIfAbsent", reflect.TypeOf((*MockITradeTagRepository)(nil).CreateIfAbsent), executionContext, tags)
}

// Delete mocks base method.
func (m *MockITradeTagRepository) Delete(executionContext context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", executionContext, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockITradeTagRepositoryMockRecorder) Delete(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockITradeTagRepository)(nil).Delete), executionContext, id)
}

// FindAllByOwner mocks base method.
func (m *MockITradeTagRepository) FindAllByOwner(executionContext context.Context, ownerID uint) ([]entities.TradeTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByOwner", executionContext, ownerID)
	ret0, _ := ret[0].([]entities.TradeTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByOwner indicates an expected call of FindAllByOwner.
func (mr *MockITradeTagRepositoryMockRecorder) FindAllByOwner(executionContext, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByOwner", reflect.TypeOf((*MockITradeTagRepository)(nil).FindAllByOwner), executionContext, ownerID)
}

// FindByIDs mocks base method.
func (m *MockITradeTagRepository) FindByIDs(executionContext context.Context, ids []uint) ([]entities.TradeTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", executionContext, ids)
	ret0, _ := ret[0].([]entities.TradeTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs.
func (mr *MockITradeTagRepositoryMockRecorder) FindByIDs(executionContext, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockITradeTagRepository)(nil).FindByIDs), executionContext, ids)
}

// FindOne mocks base method.
func (m *MockITradeTagRepository) FindOne(executionContext context.Context, id uint) (entities.TradeTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.TradeTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockITradeTagRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockITradeTagRepository)(nil).FindOne), executionContext, id)
}

// Rename mocks base method.
func (m *MockITradeTagRepository) Rename(executionContext context.Context, id uint, name string) (entities.TradeTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rename", executionContext, id, name)
	ret0, _ := ret[0].(entities.TradeTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rename indicates an expected call of Rename.
func (mr *MockITradeTagRepositoryMockRecorder) Rename(executionContext, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rename", reflect.TypeOf((*MockITradeTagRepository)(nil).Rename), executionContext, id, name)
}
