// Code generated by MockGen. DO NOT EDIT.
// Source: i_k_candle_contract_history_sync_run_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_k_candle_contract_history_sync_run_repository.go -destination=mocks/mock_i_k_candle_contract_history_sync_run_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIKCandleContractHistorySyncRunRepository is a mock of IKCandleContractHistorySyncRunRepository interface.
type MockIKCandleContractHistorySyncRunRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIKCandleContractHistorySyncRunRepositoryMockRecorder
	isgomock struct{}
}

// MockIKCandleContractHistorySyncRunRepositoryMockRecorder is the mock recorder for MockIKCandleContractHistorySyncRunRepository.
type MockIKCandleContractHistorySyncRunRepositoryMockRecorder struct {
	mock *MockIKCandleContractHistorySyncRunRepository
}

// NewMockIKCandleContractHistorySyncRunRepository creates a new mock instance.
func NewMockIKCandleContractHistorySyncRunRepository(ctrl *gomock.Controller) *MockIKCandleContractHistorySyncRunRepository {
	mock := &MockIKCandleContractHistorySyncRunRepository{ctrl: ctrl}
	mock.recorder = &MockIKCandleContractHistorySyncRunRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKCandleContractHistorySyncRunRepository) EXPECT() *MockIKCandleContractHistorySyncRunRepositoryMockRecorder {
	return m.recorder
}

// FailAllRunning mocks base method.
func (m *MockIKCandleContractHistorySyncRunRepository) FailAllRunning(executionContext context.Context, reason string, finishedAt time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailAllRunning", executionContext, reason, finishedAt)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailAllRunning indicates an expected call of FailAllRunning.
func (mr *MockIKCandleContractHistorySyncRunRepositoryMockRecorder) FailAllRunning(executionContext, reason, finishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailAllRunning", reflect.TypeOf((*MockIKCandleContractHistorySyncRunRepository)(nil).FailAllRunning), executionContext, reason, finishedAt)
}

// FindOne mocks base method.
func (m *MockIKCandleContractHistorySyncRunRepository) FindOne(executionContext context.Context, id uint) (entities.KCandleContractHistorySyncRun, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.KCandleContractHistorySyncRun)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIKCandleContractHistorySyncRunRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIKCandleContractHistorySyncRunRepository)(nil).FindOne), executionContext, id)
}

// Save mocks base method.
func (m *MockIKCandleContractHistorySyncRunRepository) Save(executionContext context.Context, syncRun entities.KCandleContractHistorySyncRun) (entities.KCandleContractHistorySyncRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, syncRun)
	ret0, _ := ret[0].(entities.KCandleContractHistorySyncRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIKCandleContractHistorySyncRunRepositoryMockRecorder) Save(executionContext, syncRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIKCandleContractHistorySyncRunRepository)(nil).Save), executionContext, syncRun)
}
