// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_market_data_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_market_data_proxy.go -destination=mocks/mock_i_contract_market_data_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractMarketDataProxy is a mock of IContractMarketDataProxy interface.
type MockIContractMarketDataProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIContractMarketDataProxyMockRecorder
	isgomock struct{}
}

// MockIContractMarketDataProxyMockRecorder is the mock recorder for MockIContractMarketDataProxy.
type MockIContractMarketDataProxyMockRecorder struct {
	mock *MockIContractMarketDataProxy
}

// NewMockIContractMarketDataProxy creates a new mock instance.
func NewMockIContractMarketDataProxy(ctrl *gomock.Controller) *MockIContractMarketDataProxy {
	mock := &MockIContractMarketDataProxy{ctrl: ctrl}
	mock.recorder = &MockIContractMarketDataProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractMarketDataProxy) EXPECT() *MockIContractMarketDataProxyMockRecorder {
	return m.recorder
}

// FetchKCandles mocks base method.
func (m *MockIContractMarketDataProxy) FetchKCandles(executionContext context.Context, window vo.KCandleFetchWindowVo) ([]vo.ContractMarketKCandleVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchKCandles", executionContext, window)
	ret0, _ := ret[0].([]vo.ContractMarketKCandleVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchKCandles indicates an expected call of FetchKCandles.
func (mr *MockIContractMarketDataProxyMockRecorder) FetchKCandles(executionContext, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchKCandles", reflect.TypeOf((*MockIContractMarketDataProxy)(nil).FetchKCandles), executionContext, window)
}
