// Code generated by MockGen. DO NOT EDIT.
// Source: i_trading_symbol_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_trading_symbol_repository.go -destination=mocks/mock_i_trading_symbol_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockITradingSymbolRepository is a mock of ITradingSymbolRepository interface.
type MockITradingSymbolRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITradingSymbolRepositoryMockRecorder
	isgomock struct{}
}

// MockITradingSymbolRepositoryMockRecorder is the mock recorder for MockITradingSymbolRepository.
type MockITradingSymbolRepositoryMockRecorder struct {
	mock *MockITradingSymbolRepository
}

// NewMockITradingSymbolRepository creates a new mock instance.
func NewMockITradingSymbolRepository(ctrl *gomock.Controller) *MockITradingSymbolRepository {
	mock := &MockITradingSymbolRepository{ctrl: ctrl}
	mock.recorder = &MockITradingSymbolRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITradingSymbolRepository) EXPECT() *MockITradingSymbolRepositoryMockRecorder {
	return m.recorder
}

// FindAll mocks base method.
func (m *MockITradingSymbolRepository) FindAll() ([]entities.TradingSymbol, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]entities.TradingSymbol)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockITradingSymbolRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockITradingSymbolRepository)(nil).FindAll))
}

// RegisterAll mocks base method.
func (m *MockITradingSymbolRepository) RegisterAll(tradingSymbols []entities.TradingSymbol) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAll", tradingSymbols)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAll indicates an expected call of RegisterAll.
func (mr *MockITradingSymbolRepositoryMockRecorder) RegisterAll(tradingSymbols any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAll", reflect.TypeOf((*MockITradingSymbolRepository)(nil).RegisterAll), tradingSymbols)
}
