// Code generated by MockGen. DO NOT EDIT.
// Source: i_assistant_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_assistant_proxy.go -destination=mocks/mock_i_assistant_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIAssistantProxy is a mock of IAssistantProxy interface.
type MockIAssistantProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIAssistantProxyMockRecorder
	isgomock struct{}
}

// MockIAssistantProxyMockRecorder is the mock recorder for MockIAssistantProxy.
type MockIAssistantProxyMockRecorder struct {
	mock *MockIAssistantProxy
}

// NewMockIAssistantProxy creates a new mock instance.
func NewMockIAssistantProxy(ctrl *gomock.Controller) *MockIAssistantProxy {
	mock := &MockIAssistantProxy{ctrl: ctrl}
	mock.recorder = &MockIAssistantProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssistantProxy) EXPECT() *MockIAssistantProxyMockRecorder {
	return m.recorder
}

// Reply mocks base method.
func (m *MockIAssistantProxy) Reply(executionContext context.Context, request vo.AssistantTurnRequestVo) (vo.AssistantReplyVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reply", executionContext, request)
	ret0, _ := ret[0].(vo.AssistantReplyVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reply indicates an expected call of Reply.
func (mr *MockIAssistantProxyMockRecorder) Reply(executionContext, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reply", reflect.TypeOf((*MockIAssistantProxy)(nil).Reply), executionContext, request)
}
