// Code generated by MockGen. DO NOT EDIT.
// Source: i_live_market_data_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_live_market_data_proxy.go -destination=mocks/mock_i_live_market_data_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockILiveMarketDataProxy is a mock of ILiveMarketDataProxy interface.
type MockILiveMarketDataProxy struct {
	ctrl     *gomock.Controller
	recorder *MockILiveMarketDataProxyMockRecorder
	isgomock struct{}
}

// MockILiveMarketDataProxyMockRecorder is the mock recorder for MockILiveMarketDataProxy.
type MockILiveMarketDataProxyMockRecorder struct {
	mock *MockILiveMarketDataProxy
}

// NewMockILiveMarketDataProxy creates a new mock instance.
func NewMockILiveMarketDataProxy(ctrl *gomock.Controller) *MockILiveMarketDataProxy {
	mock := &MockILiveMarketDataProxy{ctrl: ctrl}
	mock.recorder = &MockILiveMarketDataProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILiveMarketDataProxy) EXPECT() *MockILiveMarketDataProxyMockRecorder {
	return m.recorder
}

// FollowKCandles mocks base method.
func (m *MockILiveMarketDataProxy) FollowKCandles(executionContext context.Context, symbol string) (<-chan vo.LiveKCandleVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowKCandles", executionContext, symbol)
	ret0, _ := ret[0].(<-chan vo.LiveKCandleVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FollowKCandles indicates an expected call of FollowKCandles.
func (mr *MockILiveMarketDataProxyMockRecorder) FollowKCandles(executionContext, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowKCandles", reflect.TypeOf((*MockILiveMarketDataProxy)(nil).FollowKCandles), executionContext, symbol)
}
