// Code generated by MockGen. DO NOT EDIT.
// Source: i_market_data_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_market_data_proxy.go -destination=mocks/mock_i_market_data_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIMarketDataProxy is a mock of IMarketDataProxy interface.
type MockIMarketDataProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIMarketDataProxyMockRecorder
	isgomock struct{}
}

// MockIMarketDataProxyMockRecorder is the mock recorder for MockIMarketDataProxy.
type MockIMarketDataProxyMockRecorder struct {
	mock *MockIMarketDataProxy
}

// NewMockIMarketDataProxy creates a new mock instance.
func NewMockIMarketDataProxy(ctrl *gomock.Controller) *MockIMarketDataProxy {
	mock := &MockIMarketDataProxy{ctrl: ctrl}
	mock.recorder = &MockIMarketDataProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMarketDataProxy) EXPECT() *MockIMarketDataProxyMockRecorder {
	return m.recorder
}

// FetchKCandles mocks base method.
func (m *MockIMarketDataProxy) FetchKCandles(window vo.KCandleFetchWindowVo) ([]vo.MarketKCandleVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchKCandles", window)
	ret0, _ := ret[0].([]vo.MarketKCandleVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchKCandles indicates an expected call of FetchKCandles.
func (mr *MockIMarketDataProxyMockRecorder) FetchKCandles(window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchKCandles", reflect.TypeOf((*MockIMarketDataProxy)(nil).FetchKCandles), window)
}
