// Code generated by MockGen. DO NOT EDIT.
// Source: i_strategy_adoption_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_strategy_adoption_repository.go -destination=mocks/mock_i_strategy_adoption_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIStrategyAdoptionRepository is a mock of IStrategyAdoptionRepository interface.
type MockIStrategyAdoptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyAdoptionRepositoryMockRecorder
	isgomock struct{}
}

// MockIStrategyAdoptionRepositoryMockRecorder is the mock recorder for MockIStrategyAdoptionRepository.
type MockIStrategyAdoptionRepositoryMockRecorder struct {
	mock *MockIStrategyAdoptionRepository
}

// NewMockIStrategyAdoptionRepository creates a new mock instance.
func NewMockIStrategyAdoptionRepository(ctrl *gomock.Controller) *MockIStrategyAdoptionRepository {
	mock := &MockIStrategyAdoptionRepository{ctrl: ctrl}
	mock.recorder = &MockIStrategyAdoptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategyAdoptionRepository) EXPECT() *MockIStrategyAdoptionRepositoryMockRecorder {
	return m.recorder
}

// Abandon mocks base method.
func (m *MockIStrategyAdoptionRepository) Abandon(executionContext context.Context, userID, strategyID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abandon", executionContext, userID, strategyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Abandon indicates an expected call of Abandon.
func (mr *MockIStrategyAdoptionRepositoryMockRecorder) Abandon(executionContext, userID, strategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abandon", reflect.TypeOf((*MockIStrategyAdoptionRepository)(nil).Abandon), executionContext, userID, strategyID)
}

// Adopt mocks base method.
func (m *MockIStrategyAdoptionRepository) Adopt(executionContext context.Context, userID, strategyID uint, adoptedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Adopt", executionContext, userID, strategyID, adoptedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Adopt indicates an expected call of Adopt.
func (mr *MockIStrategyAdoptionRepositoryMockRecorder) Adopt(executionContext, userID, strategyID, adoptedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Adopt", reflect.TypeOf((*MockIStrategyAdoptionRepository)(nil).Adopt), executionContext, userID, strategyID, adoptedAt)
}
