// Code generated by MockGen. DO NOT EDIT.
// Source: i_connector_authorization_request_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_connector_authorization_request_repository.go -destination=mocks/mock_i_connector_authorization_request_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIConnectorAuthorizationRequestRepository is a mock of IConnectorAuthorizationRequestRepository interface.
type MockIConnectorAuthorizationRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIConnectorAuthorizationRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockIConnectorAuthorizationRequestRepositoryMockRecorder is the mock recorder for MockIConnectorAuthorizationRequestRepository.
type MockIConnectorAuthorizationRequestRepositoryMockRecorder struct {
	mock *MockIConnectorAuthorizationRequestRepository
}

// NewMockIConnectorAuthorizationRequestRepository creates a new mock instance.
func NewMockIConnectorAuthorizationRequestRepository(ctrl *gomock.Controller) *MockIConnectorAuthorizationRequestRepository {
	mock := &MockIConnectorAuthorizationRequestRepository{ctrl: ctrl}
	mock.recorder = &MockIConnectorAuthorizationRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConnectorAuthorizationRequestRepository) EXPECT() *MockIConnectorAuthorizationRequestRepositoryMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockIConnectorAuthorizationRequestRepository) Approve(executionContext context.Context, requestID uint, decidedAt time.Time, authorizationCode entities.ConnectorAuthorizationCode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", executionContext, requestID, decidedAt, authorizationCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockIConnectorAuthorizationRequestRepositoryMockRecorder) Approve(executionContext, requestID, decidedAt, authorizationCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockIConnectorAuthorizationRequestRepository)(nil).Approve), executionContext, requestID, decidedAt, authorizationCode)
}

// Deny mocks base method.
func (m *MockIConnectorAuthorizationRequestRepository) Deny(executionContext context.Context, requestID uint, decidedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deny", executionContext, requestID, decidedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deny indicates an expected call of Deny.
func (mr *MockIConnectorAuthorizationRequestRepositoryMockRecorder) Deny(executionContext, requestID, decidedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deny", reflect.TypeOf((*MockIConnectorAuthorizationRequestRepository)(nil).Deny), executionContext, requestID, decidedAt)
}

// FindOneByRequestIdentifier mocks base method.
func (m *MockIConnectorAuthorizationRequestRepository) FindOneByRequestIdentifier(executionContext context.Context, requestIdentifier string) (entities.ConnectorAuthorizationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByRequestIdentifier", executionContext, requestIdentifier)
	ret0, _ := ret[0].(entities.ConnectorAuthorizationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByRequestIdentifier indicates an expected call of FindOneByRequestIdentifier.
func (mr *MockIConnectorAuthorizationRequestRepositoryMockRecorder) FindOneByRequestIdentifier(executionContext, requestIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByRequestIdentifier", reflect.TypeOf((*MockIConnectorAuthorizationRequestRepository)(nil).FindOneByRequestIdentifier), executionContext, requestIdentifier)
}

// Save mocks base method.
func (m *MockIConnectorAuthorizationRequestRepository) Save(executionContext context.Context, authorizationRequest entities.ConnectorAuthorizationRequest) (entities.ConnectorAuthorizationRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, authorizationRequest)
	ret0, _ := ret[0].(entities.ConnectorAuthorizationRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIConnectorAuthorizationRequestRepositoryMockRecorder) Save(executionContext, authorizationRequest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIConnectorAuthorizationRequestRepository)(nil).Save), executionContext, authorizationRequest)
}
