// Code generated by MockGen. DO NOT EDIT.
// Source: i_message_delivery_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_message_delivery_proxy.go -destination=mocks/mock_i_message_delivery_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIMessageDeliveryProxy is a mock of IMessageDeliveryProxy interface.
type MockIMessageDeliveryProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIMessageDeliveryProxyMockRecorder
	isgomock struct{}
}

// MockIMessageDeliveryProxyMockRecorder is the mock recorder for MockIMessageDeliveryProxy.
type MockIMessageDeliveryProxyMockRecorder struct {
	mock *MockIMessageDeliveryProxy
}

// NewMockIMessageDeliveryProxy creates a new mock instance.
func NewMockIMessageDeliveryProxy(ctrl *gomock.Controller) *MockIMessageDeliveryProxy {
	mock := &MockIMessageDeliveryProxy{ctrl: ctrl}
	mock.recorder = &MockIMessageDeliveryProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMessageDeliveryProxy) EXPECT() *MockIMessageDeliveryProxyMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockIMessageDeliveryProxy) Deliver(executionContext context.Context, credential vo.MessageDeliveryCredentialVo, message string) (vo.DeliveryFailureReasonVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", executionContext, credential, message)
	ret0, _ := ret[0].(vo.DeliveryFailureReasonVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deliver indicates an expected call of Deliver.
func (mr *MockIMessageDeliveryProxyMockRecorder) Deliver(executionContext, credential, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockIMessageDeliveryProxy)(nil).Deliver), executionContext, credential, message)
}
