// Code generated by MockGen. DO NOT EDIT.
// Source: i_k_candle_history_sync_run_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_k_candle_history_sync_run_repository.go -destination=mocks/mock_i_k_candle_history_sync_run_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIKCandleHistorySyncRunRepository is a mock of IKCandleHistorySyncRunRepository interface.
type MockIKCandleHistorySyncRunRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIKCandleHistorySyncRunRepositoryMockRecorder
	isgomock struct{}
}

// MockIKCandleHistorySyncRunRepositoryMockRecorder is the mock recorder for MockIKCandleHistorySyncRunRepository.
type MockIKCandleHistorySyncRunRepositoryMockRecorder struct {
	mock *MockIKCandleHistorySyncRunRepository
}

// NewMockIKCandleHistorySyncRunRepository creates a new mock instance.
func NewMockIKCandleHistorySyncRunRepository(ctrl *gomock.Controller) *MockIKCandleHistorySyncRunRepository {
	mock := &MockIKCandleHistorySyncRunRepository{ctrl: ctrl}
	mock.recorder = &MockIKCandleHistorySyncRunRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKCandleHistorySyncRunRepository) EXPECT() *MockIKCandleHistorySyncRunRepositoryMockRecorder {
	return m.recorder
}

// CountRunning mocks base method.
func (m *MockIKCandleHistorySyncRunRepository) CountRunning(executionContext context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRunning", executionContext)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRunning indicates an expected call of CountRunning.
func (mr *MockIKCandleHistorySyncRunRepositoryMockRecorder) CountRunning(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRunning", reflect.TypeOf((*MockIKCandleHistorySyncRunRepository)(nil).CountRunning), executionContext)
}

// FailAllRunning mocks base method.
func (m *MockIKCandleHistorySyncRunRepository) FailAllRunning(executionContext context.Context, reason string, finishedAt time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailAllRunning", executionContext, reason, finishedAt)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FailAllRunning indicates an expected call of FailAllRunning.
func (mr *MockIKCandleHistorySyncRunRepositoryMockRecorder) FailAllRunning(executionContext, reason, finishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailAllRunning", reflect.TypeOf((*MockIKCandleHistorySyncRunRepository)(nil).FailAllRunning), executionContext, reason, finishedAt)
}

// FindOne mocks base method.
func (m *MockIKCandleHistorySyncRunRepository) FindOne(executionContext context.Context, id uint) (entities.KCandleHistorySyncRun, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.KCandleHistorySyncRun)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIKCandleHistorySyncRunRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIKCandleHistorySyncRunRepository)(nil).FindOne), executionContext, id)
}

// Save mocks base method.
func (m *MockIKCandleHistorySyncRunRepository) Save(executionContext context.Context, syncRun entities.KCandleHistorySyncRun) (entities.KCandleHistorySyncRun, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, syncRun)
	ret0, _ := ret[0].(entities.KCandleHistorySyncRun)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIKCandleHistorySyncRunRepositoryMockRecorder) Save(executionContext, syncRun any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIKCandleHistorySyncRunRepository)(nil).Save), executionContext, syncRun)
}
