// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_funding_rate_settlement_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_funding_rate_settlement_repository.go -destination=mocks/mock_i_contract_funding_rate_settlement_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domains "github.com/CodeMachine0121/go-trading/internal/domain/models/domains"
	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractFundingRateSettlementRepository is a mock of IContractFundingRateSettlementRepository interface.
type MockIContractFundingRateSettlementRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContractFundingRateSettlementRepositoryMockRecorder
	isgomock struct{}
}

// MockIContractFundingRateSettlementRepositoryMockRecorder is the mock recorder for MockIContractFundingRateSettlementRepository.
type MockIContractFundingRateSettlementRepositoryMockRecorder struct {
	mock *MockIContractFundingRateSettlementRepository
}

// NewMockIContractFundingRateSettlementRepository creates a new mock instance.
func NewMockIContractFundingRateSettlementRepository(ctrl *gomock.Controller) *MockIContractFundingRateSettlementRepository {
	mock := &MockIContractFundingRateSettlementRepository{ctrl: ctrl}
	mock.recorder = &MockIContractFundingRateSettlementRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractFundingRateSettlementRepository) EXPECT() *MockIContractFundingRateSettlementRepositoryMockRecorder {
	return m.recorder
}

// FindInRange mocks base method.
func (m *MockIContractFundingRateSettlementRepository) FindInRange(executionContext context.Context, query domains.KCandleQueryDomain, limit int) ([]entities.ContractFundingRateSettlement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInRange", executionContext, query, limit)
	ret0, _ := ret[0].([]entities.ContractFundingRateSettlement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInRange indicates an expected call of FindInRange.
func (mr *MockIContractFundingRateSettlementRepositoryMockRecorder) FindInRange(executionContext, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInRange", reflect.TypeOf((*MockIContractFundingRateSettlementRepository)(nil).FindInRange), executionContext, query, limit)
}

// FindLatest mocks base method.
func (m *MockIContractFundingRateSettlementRepository) FindLatest(executionContext context.Context, symbol string) (entities.ContractFundingRateSettlement, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatest", executionContext, symbol)
	ret0, _ := ret[0].(entities.ContractFundingRateSettlement)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindLatest indicates an expected call of FindLatest.
func (mr *MockIContractFundingRateSettlementRepositoryMockRecorder) FindLatest(executionContext, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatest", reflect.TypeOf((*MockIContractFundingRateSettlementRepository)(nil).FindLatest), executionContext, symbol)
}

// SaveAllIfAbsent mocks base method.
func (m *MockIContractFundingRateSettlementRepository) SaveAllIfAbsent(executionContext context.Context, settlements []entities.ContractFundingRateSettlement) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAllIfAbsent", executionContext, settlements)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAllIfAbsent indicates an expected call of SaveAllIfAbsent.
func (mr *MockIContractFundingRateSettlementRepositoryMockRecorder) SaveAllIfAbsent(executionContext, settlements any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAllIfAbsent", reflect.TypeOf((*MockIContractFundingRateSettlementRepository)(nil).SaveAllIfAbsent), executionContext, settlements)
}
