// Code generated by MockGen. DO NOT EDIT.
// Source: i_connector_client_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_connector_client_repository.go -destination=mocks/mock_i_connector_client_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIConnectorClientRepository is a mock of IConnectorClientRepository interface.
type MockIConnectorClientRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIConnectorClientRepositoryMockRecorder
	isgomock struct{}
}

// MockIConnectorClientRepositoryMockRecorder is the mock recorder for MockIConnectorClientRepository.
type MockIConnectorClientRepositoryMockRecorder struct {
	mock *MockIConnectorClientRepository
}

// NewMockIConnectorClientRepository creates a new mock instance.
func NewMockIConnectorClientRepository(ctrl *gomock.Controller) *MockIConnectorClientRepository {
	mock := &MockIConnectorClientRepository{ctrl: ctrl}
	mock.recorder = &MockIConnectorClientRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConnectorClientRepository) EXPECT() *MockIConnectorClientRepositoryMockRecorder {
	return m.recorder
}

// FindOneByClientIdentifier mocks base method.
func (m *MockIConnectorClientRepository) FindOneByClientIdentifier(executionContext context.Context, clientIdentifier string) (entities.ConnectorClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByClientIdentifier", executionContext, clientIdentifier)
	ret0, _ := ret[0].(entities.ConnectorClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByClientIdentifier indicates an expected call of FindOneByClientIdentifier.
func (mr *MockIConnectorClientRepositoryMockRecorder) FindOneByClientIdentifier(executionContext, clientIdentifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByClientIdentifier", reflect.TypeOf((*MockIConnectorClientRepository)(nil).FindOneByClientIdentifier), executionContext, clientIdentifier)
}

// Save mocks base method.
func (m *MockIConnectorClientRepository) Save(executionContext context.Context, connectorClient entities.ConnectorClient) (entities.ConnectorClient, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, connectorClient)
	ret0, _ := ret[0].(entities.ConnectorClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIConnectorClientRepositoryMockRecorder) Save(executionContext, connectorClient any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIConnectorClientRepository)(nil).Save), executionContext, connectorClient)
}
