// Code generated by MockGen. DO NOT EDIT.
// Source: i_secret_seal_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_secret_seal_proxy.go -destination=mocks/mock_i_secret_seal_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockISecretSealProxy is a mock of ISecretSealProxy interface.
type MockISecretSealProxy struct {
	ctrl     *gomock.Controller
	recorder *MockISecretSealProxyMockRecorder
	isgomock struct{}
}

// MockISecretSealProxyMockRecorder is the mock recorder for MockISecretSealProxy.
type MockISecretSealProxyMockRecorder struct {
	mock *MockISecretSealProxy
}

// NewMockISecretSealProxy creates a new mock instance.
func NewMockISecretSealProxy(ctrl *gomock.Controller) *MockISecretSealProxy {
	mock := &MockISecretSealProxy{ctrl: ctrl}
	mock.recorder = &MockISecretSealProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISecretSealProxy) EXPECT() *MockISecretSealProxyMockRecorder {
	return m.recorder
}

// Seal mocks base method.
func (m *MockISecretSealProxy) Seal(plaintext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seal", plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seal indicates an expected call of Seal.
func (mr *MockISecretSealProxyMockRecorder) Seal(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seal", reflect.TypeOf((*MockISecretSealProxy)(nil).Seal), plaintext)
}

// Unseal mocks base method.
func (m *MockISecretSealProxy) Unseal(sealed string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unseal", sealed)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unseal indicates an expected call of Unseal.
func (mr *MockISecretSealProxyMockRecorder) Unseal(sealed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unseal", reflect.TypeOf((*MockISecretSealProxy)(nil).Unseal), sealed)
}
