// Code generated by MockGen. DO NOT EDIT.
// Source: i_strategy_bot_run_record_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_strategy_bot_run_record_repository.go -destination=mocks/mock_i_strategy_bot_run_record_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIStrategyBotRunRecordRepository is a mock of IStrategyBotRunRecordRepository interface.
type MockIStrategyBotRunRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyBotRunRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockIStrategyBotRunRecordRepositoryMockRecorder is the mock recorder for MockIStrategyBotRunRecordRepository.
type MockIStrategyBotRunRecordRepositoryMockRecorder struct {
	mock *MockIStrategyBotRunRecordRepository
}

// NewMockIStrategyBotRunRecordRepository creates a new mock instance.
func NewMockIStrategyBotRunRecordRepository(ctrl *gomock.Controller) *MockIStrategyBotRunRecordRepository {
	mock := &MockIStrategyBotRunRecordRepository{ctrl: ctrl}
	mock.recorder = &MockIStrategyBotRunRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategyBotRunRecordRepository) EXPECT() *MockIStrategyBotRunRecordRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockIStrategyBotRunRecordRepository) Append(executionContext context.Context, strategyBotID uint, ranAt time.Time, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", executionContext, strategyBotID, ranAt, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockIStrategyBotRunRecordRepositoryMockRecorder) Append(executionContext, strategyBotID, ranAt, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockIStrategyBotRunRecordRepository)(nil).Append), executionContext, strategyBotID, ranAt, result)
}

// FindLatestByBot mocks base method.
func (m *MockIStrategyBotRunRecordRepository) FindLatestByBot(executionContext context.Context, strategyBotID uint) ([]entities.StrategyBotRunRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestByBot", executionContext, strategyBotID)
	ret0, _ := ret[0].([]entities.StrategyBotRunRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestByBot indicates an expected call of FindLatestByBot.
func (mr *MockIStrategyBotRunRecordRepositoryMockRecorder) FindLatestByBot(executionContext, strategyBotID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestByBot", reflect.TypeOf((*MockIStrategyBotRunRecordRepository)(nil).FindLatestByBot), executionContext, strategyBotID)
}
