// Code generated by MockGen. DO NOT EDIT.
// Source: i_indicator_script_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_indicator_script_proxy.go -destination=mocks/mock_i_indicator_script_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domains "github.com/CodeMachine0121/go-trading/internal/domain/models/domains"
	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIIndicatorScriptProxy is a mock of IIndicatorScriptProxy interface.
type MockIIndicatorScriptProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIIndicatorScriptProxyMockRecorder
	isgomock struct{}
}

// MockIIndicatorScriptProxyMockRecorder is the mock recorder for MockIIndicatorScriptProxy.
type MockIIndicatorScriptProxyMockRecorder struct {
	mock *MockIIndicatorScriptProxy
}

// NewMockIIndicatorScriptProxy creates a new mock instance.
func NewMockIIndicatorScriptProxy(ctrl *gomock.Controller) *MockIIndicatorScriptProxy {
	mock := &MockIIndicatorScriptProxy{ctrl: ctrl}
	mock.recorder = &MockIIndicatorScriptProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIIndicatorScriptProxy) EXPECT() *MockIIndicatorScriptProxyMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIIndicatorScriptProxy) Execute(executionContext context.Context, script string, resultType domains.IndicatorResultTypeDomain, kCandles []vo.KCandleVo, parameters domains.StrategyParametersDomain) (map[string]vo.IndicatorValueVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", executionContext, script, resultType, kCandles, parameters)
	ret0, _ := ret[0].(map[string]vo.IndicatorValueVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIIndicatorScriptProxyMockRecorder) Execute(executionContext, script, resultType, kCandles, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIIndicatorScriptProxy)(nil).Execute), executionContext, script, resultType, kCandles, parameters)
}

// ExecuteForEachCandle mocks base method.
func (m *MockIIndicatorScriptProxy) ExecuteForEachCandle(executionContext context.Context, script string, resultType domains.IndicatorResultTypeDomain, kCandles []vo.KCandleVo, parameters domains.StrategyParametersDomain) ([]map[string]vo.IndicatorValueVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteForEachCandle", executionContext, script, resultType, kCandles, parameters)
	ret0, _ := ret[0].([]map[string]vo.IndicatorValueVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteForEachCandle indicates an expected call of ExecuteForEachCandle.
func (mr *MockIIndicatorScriptProxyMockRecorder) ExecuteForEachCandle(executionContext, script, resultType, kCandles, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteForEachCandle", reflect.TypeOf((*MockIIndicatorScriptProxy)(nil).ExecuteForEachCandle), executionContext, script, resultType, kCandles, parameters)
}
