// Code generated by MockGen. DO NOT EDIT.
// Source: i_published_strategy_script_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_published_strategy_script_repository.go -destination=mocks/mock_i_published_strategy_script_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIPublishedStrategyScriptRepository is a mock of IPublishedStrategyScriptRepository interface.
type MockIPublishedStrategyScriptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPublishedStrategyScriptRepositoryMockRecorder
	isgomock struct{}
}

// MockIPublishedStrategyScriptRepositoryMockRecorder is the mock recorder for MockIPublishedStrategyScriptRepository.
type MockIPublishedStrategyScriptRepositoryMockRecorder struct {
	mock *MockIPublishedStrategyScriptRepository
}

// NewMockIPublishedStrategyScriptRepository creates a new mock instance.
func NewMockIPublishedStrategyScriptRepository(ctrl *gomock.Controller) *MockIPublishedStrategyScriptRepository {
	mock := &MockIPublishedStrategyScriptRepository{ctrl: ctrl}
	mock.recorder = &MockIPublishedStrategyScriptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPublishedStrategyScriptRepository) EXPECT() *MockIPublishedStrategyScriptRepositoryMockRecorder {
	return m.recorder
}

// FindOne mocks base method.
func (m *MockIPublishedStrategyScriptRepository) FindOne(executionContext context.Context, strategyScriptID uint) (entities.PublishedStrategyScript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, strategyScriptID)
	ret0, _ := ret[0].(entities.PublishedStrategyScript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIPublishedStrategyScriptRepositoryMockRecorder) FindOne(executionContext, strategyScriptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIPublishedStrategyScriptRepository)(nil).FindOne), executionContext, strategyScriptID)
}

// Publish mocks base method.
func (m *MockIPublishedStrategyScriptRepository) Publish(executionContext context.Context, strategyScriptID uint, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", executionContext, strategyScriptID, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockIPublishedStrategyScriptRepositoryMockRecorder) Publish(executionContext, strategyScriptID, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIPublishedStrategyScriptRepository)(nil).Publish), executionContext, strategyScriptID, publishedAt)
}

// Withdraw mocks base method.
func (m *MockIPublishedStrategyScriptRepository) Withdraw(executionContext context.Context, strategyScriptID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", executionContext, strategyScriptID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockIPublishedStrategyScriptRepositoryMockRecorder) Withdraw(executionContext, strategyScriptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockIPublishedStrategyScriptRepository)(nil).Withdraw), executionContext, strategyScriptID)
}
