// Code generated by MockGen. DO NOT EDIT.
// Source: i_k_candle_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_k_candle_repository.go -destination=mocks/mock_i_k_candle_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	domains "github.com/CodeMachine0121/go-trading/internal/domain/models/domains"
	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIKCandleRepository is a mock of IKCandleRepository interface.
type MockIKCandleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIKCandleRepositoryMockRecorder
	isgomock struct{}
}

// MockIKCandleRepositoryMockRecorder is the mock recorder for MockIKCandleRepository.
type MockIKCandleRepositoryMockRecorder struct {
	mock *MockIKCandleRepository
}

// NewMockIKCandleRepository creates a new mock instance.
func NewMockIKCandleRepository(ctrl *gomock.Controller) *MockIKCandleRepository {
	mock := &MockIKCandleRepository{ctrl: ctrl}
	mock.recorder = &MockIKCandleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKCandleRepository) EXPECT() *MockIKCandleRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIKCandleRepository) Delete(symbol string, openTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", symbol, openTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIKCandleRepositoryMockRecorder) Delete(symbol, openTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIKCandleRepository)(nil).Delete), symbol, openTime)
}

// FindInRange mocks base method.
func (m *MockIKCandleRepository) FindInRange(query domains.KCandleQueryDomain, limit int) ([]entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInRange", query, limit)
	ret0, _ := ret[0].([]entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInRange indicates an expected call of FindInRange.
func (mr *MockIKCandleRepositoryMockRecorder) FindInRange(query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInRange", reflect.TypeOf((*MockIKCandleRepository)(nil).FindInRange), query, limit)
}

// FindOne mocks base method.
func (m *MockIKCandleRepository) FindOne(symbol string, openTime time.Time) (entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", symbol, openTime)
	ret0, _ := ret[0].(entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIKCandleRepositoryMockRecorder) FindOne(symbol, openTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIKCandleRepository)(nil).FindOne), symbol, openTime)
}

// Save mocks base method.
func (m *MockIKCandleRepository) Save(kCandle entities.KCandle) (entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", kCandle)
	ret0, _ := ret[0].(entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIKCandleRepositoryMockRecorder) Save(kCandle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIKCandleRepository)(nil).Save), kCandle)
}

// Update mocks base method.
func (m *MockIKCandleRepository) Update(kCandle entities.KCandle) (entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", kCandle)
	ret0, _ := ret[0].(entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIKCandleRepositoryMockRecorder) Update(kCandle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIKCandleRepository)(nil).Update), kCandle)
}
