// Code generated by MockGen. DO NOT EDIT.
// Source: i_k_candle_contract_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_k_candle_contract_repository.go -destination=mocks/mock_i_k_candle_contract_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domains "github.com/CodeMachine0121/go-trading/internal/domain/models/domains"
	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIKCandleContractRepository is a mock of IKCandleContractRepository interface.
type MockIKCandleContractRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIKCandleContractRepositoryMockRecorder
	isgomock struct{}
}

// MockIKCandleContractRepositoryMockRecorder is the mock recorder for MockIKCandleContractRepository.
type MockIKCandleContractRepositoryMockRecorder struct {
	mock *MockIKCandleContractRepository
}

// NewMockIKCandleContractRepository creates a new mock instance.
func NewMockIKCandleContractRepository(ctrl *gomock.Controller) *MockIKCandleContractRepository {
	mock := &MockIKCandleContractRepository{ctrl: ctrl}
	mock.recorder = &MockIKCandleContractRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKCandleContractRepository) EXPECT() *MockIKCandleContractRepositoryMockRecorder {
	return m.recorder
}

// CountInRange mocks base method.
func (m *MockIKCandleContractRepository) CountInRange(executionContext context.Context, symbol string, startTime, endTime time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInRange", executionContext, symbol, startTime, endTime)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInRange indicates an expected call of CountInRange.
func (mr *MockIKCandleContractRepositoryMockRecorder) CountInRange(executionContext, symbol, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInRange", reflect.TypeOf((*MockIKCandleContractRepository)(nil).CountInRange), executionContext, symbol, startTime, endTime)
}

// Delete mocks base method.
func (m *MockIKCandleContractRepository) Delete(executionContext context.Context, symbol string, openTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", executionContext, symbol, openTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIKCandleContractRepositoryMockRecorder) Delete(executionContext, symbol, openTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIKCandleContractRepository)(nil).Delete), executionContext, symbol, openTime)
}

// FindDistinctSymbols mocks base method.
func (m *MockIKCandleContractRepository) FindDistinctSymbols(executionContext context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDistinctSymbols", executionContext)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDistinctSymbols indicates an expected call of FindDistinctSymbols.
func (mr *MockIKCandleContractRepositoryMockRecorder) FindDistinctSymbols(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDistinctSymbols", reflect.TypeOf((*MockIKCandleContractRepository)(nil).FindDistinctSymbols), executionContext)
}

// FindInRange mocks base method.
func (m *MockIKCandleContractRepository) FindInRange(executionContext context.Context, query domains.KCandleQueryDomain, limit int) ([]entities.KCandleContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInRange", executionContext, query, limit)
	ret0, _ := ret[0].([]entities.KCandleContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInRange indicates an expected call of FindInRange.
func (mr *MockIKCandleContractRepositoryMockRecorder) FindInRange(executionContext, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInRange", reflect.TypeOf((*MockIKCandleContractRepository)(nil).FindInRange), executionContext, query, limit)
}

// FindLatest mocks base method.
func (m *MockIKCandleContractRepository) FindLatest(executionContext context.Context, symbol string, limit int) ([]entities.KCandleContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatest", executionContext, symbol, limit)
	ret0, _ := ret[0].([]entities.KCandleContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatest indicates an expected call of FindLatest.
func (mr *MockIKCandleContractRepositoryMockRecorder) FindLatest(executionContext, symbol, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatest", reflect.TypeOf((*MockIKCandleContractRepository)(nil).FindLatest), executionContext, symbol, limit)
}

// FindOne mocks base method.
func (m *MockIKCandleContractRepository) FindOne(executionContext context.Context, symbol string, openTime time.Time) (entities.KCandleContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, symbol, openTime)
	ret0, _ := ret[0].(entities.KCandleContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIKCandleContractRepositoryMockRecorder) FindOne(executionContext, symbol, openTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIKCandleContractRepository)(nil).FindOne), executionContext, symbol, openTime)
}

// Save mocks base method.
func (m *MockIKCandleContractRepository) Save(executionContext context.Context, kCandleContract entities.KCandleContract) (entities.KCandleContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, kCandleContract)
	ret0, _ := ret[0].(entities.KCandleContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIKCandleContractRepositoryMockRecorder) Save(executionContext, kCandleContract any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIKCandleContractRepository)(nil).Save), executionContext, kCandleContract)
}

// SaveAllIfAbsent mocks base method.
func (m *MockIKCandleContractRepository) SaveAllIfAbsent(executionContext context.Context, kCandleContracts []entities.KCandleContract) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAllIfAbsent", executionContext, kCandleContracts)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAllIfAbsent indicates an expected call of SaveAllIfAbsent.
func (mr *MockIKCandleContractRepositoryMockRecorder) SaveAllIfAbsent(executionContext, kCandleContracts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAllIfAbsent", reflect.TypeOf((*MockIKCandleContractRepository)(nil).SaveAllIfAbsent), executionContext, kCandleContracts)
}

// Update mocks base method.
func (m *MockIKCandleContractRepository) Update(executionContext context.Context, kCandleContract entities.KCandleContract) (entities.KCandleContract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", executionContext, kCandleContract)
	ret0, _ := ret[0].(entities.KCandleContract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIKCandleContractRepositoryMockRecorder) Update(executionContext, kCandleContract any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIKCandleContractRepository)(nil).Update), executionContext, kCandleContract)
}
