// Code generated by MockGen. DO NOT EDIT.
// Source: i_connector_authorization_code_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_connector_authorization_code_repository.go -destination=mocks/mock_i_connector_authorization_code_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIConnectorAuthorizationCodeRepository is a mock of IConnectorAuthorizationCodeRepository interface.
type MockIConnectorAuthorizationCodeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIConnectorAuthorizationCodeRepositoryMockRecorder
	isgomock struct{}
}

// MockIConnectorAuthorizationCodeRepositoryMockRecorder is the mock recorder for MockIConnectorAuthorizationCodeRepository.
type MockIConnectorAuthorizationCodeRepositoryMockRecorder struct {
	mock *MockIConnectorAuthorizationCodeRepository
}

// NewMockIConnectorAuthorizationCodeRepository creates a new mock instance.
func NewMockIConnectorAuthorizationCodeRepository(ctrl *gomock.Controller) *MockIConnectorAuthorizationCodeRepository {
	mock := &MockIConnectorAuthorizationCodeRepository{ctrl: ctrl}
	mock.recorder = &MockIConnectorAuthorizationCodeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConnectorAuthorizationCodeRepository) EXPECT() *MockIConnectorAuthorizationCodeRepositoryMockRecorder {
	return m.recorder
}

// FindOneByDigest mocks base method.
func (m *MockIConnectorAuthorizationCodeRepository) FindOneByDigest(executionContext context.Context, codeDigest string) (entities.ConnectorAuthorizationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByDigest", executionContext, codeDigest)
	ret0, _ := ret[0].(entities.ConnectorAuthorizationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByDigest indicates an expected call of FindOneByDigest.
func (mr *MockIConnectorAuthorizationCodeRepositoryMockRecorder) FindOneByDigest(executionContext, codeDigest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByDigest", reflect.TypeOf((*MockIConnectorAuthorizationCodeRepository)(nil).FindOneByDigest), executionContext, codeDigest)
}

// Redeem mocks base method.
func (m *MockIConnectorAuthorizationCodeRepository) Redeem(executionContext context.Context, codeID uint, session entities.Session) (entities.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Redeem", executionContext, codeID, session)
	ret0, _ := ret[0].(entities.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Redeem indicates an expected call of Redeem.
func (mr *MockIConnectorAuthorizationCodeRepositoryMockRecorder) Redeem(executionContext, codeID, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redeem", reflect.TypeOf((*MockIConnectorAuthorizationCodeRepository)(nil).Redeem), executionContext, codeID, session)
}
