// Code generated by MockGen. DO NOT EDIT.
// Source: i_strategy_script_adoption_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_strategy_script_adoption_repository.go -destination=mocks/mock_i_strategy_script_adoption_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIStrategyScriptAdoptionRepository is a mock of IStrategyScriptAdoptionRepository interface.
type MockIStrategyScriptAdoptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyScriptAdoptionRepositoryMockRecorder
	isgomock struct{}
}

// MockIStrategyScriptAdoptionRepositoryMockRecorder is the mock recorder for MockIStrategyScriptAdoptionRepository.
type MockIStrategyScriptAdoptionRepositoryMockRecorder struct {
	mock *MockIStrategyScriptAdoptionRepository
}

// NewMockIStrategyScriptAdoptionRepository creates a new mock instance.
func NewMockIStrategyScriptAdoptionRepository(ctrl *gomock.Controller) *MockIStrategyScriptAdoptionRepository {
	mock := &MockIStrategyScriptAdoptionRepository{ctrl: ctrl}
	mock.recorder = &MockIStrategyScriptAdoptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategyScriptAdoptionRepository) EXPECT() *MockIStrategyScriptAdoptionRepositoryMockRecorder {
	return m.recorder
}

// Abandon mocks base method.
func (m *MockIStrategyScriptAdoptionRepository) Abandon(executionContext context.Context, userID, strategyScriptID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abandon", executionContext, userID, strategyScriptID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Abandon indicates an expected call of Abandon.
func (mr *MockIStrategyScriptAdoptionRepositoryMockRecorder) Abandon(executionContext, userID, strategyScriptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abandon", reflect.TypeOf((*MockIStrategyScriptAdoptionRepository)(nil).Abandon), executionContext, userID, strategyScriptID)
}

// Adopt mocks base method.
func (m *MockIStrategyScriptAdoptionRepository) Adopt(executionContext context.Context, userID, strategyScriptID uint, adoptedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Adopt", executionContext, userID, strategyScriptID, adoptedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Adopt indicates an expected call of Adopt.
func (mr *MockIStrategyScriptAdoptionRepositoryMockRecorder) Adopt(executionContext, userID, strategyScriptID, adoptedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Adopt", reflect.TypeOf((*MockIStrategyScriptAdoptionRepository)(nil).Adopt), executionContext, userID, strategyScriptID, adoptedAt)
}
