// Code generated by MockGen. DO NOT EDIT.
// Source: i_strategy_script_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_strategy_script_repository.go -destination=mocks/mock_i_strategy_script_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIStrategyScriptRepository is a mock of IStrategyScriptRepository interface.
type MockIStrategyScriptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyScriptRepositoryMockRecorder
	isgomock struct{}
}

// MockIStrategyScriptRepositoryMockRecorder is the mock recorder for MockIStrategyScriptRepository.
type MockIStrategyScriptRepositoryMockRecorder struct {
	mock *MockIStrategyScriptRepository
}

// NewMockIStrategyScriptRepository creates a new mock instance.
func NewMockIStrategyScriptRepository(ctrl *gomock.Controller) *MockIStrategyScriptRepository {
	mock := &MockIStrategyScriptRepository{ctrl: ctrl}
	mock.recorder = &MockIStrategyScriptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategyScriptRepository) EXPECT() *MockIStrategyScriptRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIStrategyScriptRepository) Delete(executionContext context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", executionContext, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIStrategyScriptRepositoryMockRecorder) Delete(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIStrategyScriptRepository)(nil).Delete), executionContext, id)
}

// FindAllAdoptedBy mocks base method.
func (m *MockIStrategyScriptRepository) FindAllAdoptedBy(executionContext context.Context, userID uint) ([]entities.PublishedStrategyScript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllAdoptedBy", executionContext, userID)
	ret0, _ := ret[0].([]entities.PublishedStrategyScript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllAdoptedBy indicates an expected call of FindAllAdoptedBy.
func (mr *MockIStrategyScriptRepositoryMockRecorder) FindAllAdoptedBy(executionContext, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllAdoptedBy", reflect.TypeOf((*MockIStrategyScriptRepository)(nil).FindAllAdoptedBy), executionContext, userID)
}

// FindAllOwnedBy mocks base method.
func (m *MockIStrategyScriptRepository) FindAllOwnedBy(executionContext context.Context, ownerID uint) ([]entities.StrategyScript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllOwnedBy", executionContext, ownerID)
	ret0, _ := ret[0].([]entities.StrategyScript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllOwnedBy indicates an expected call of FindAllOwnedBy.
func (mr *MockIStrategyScriptRepositoryMockRecorder) FindAllOwnedBy(executionContext, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllOwnedBy", reflect.TypeOf((*MockIStrategyScriptRepository)(nil).FindAllOwnedBy), executionContext, ownerID)
}

// FindAllPublished mocks base method.
func (m *MockIStrategyScriptRepository) FindAllPublished(executionContext context.Context) ([]entities.PublishedStrategyScript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllPublished", executionContext)
	ret0, _ := ret[0].([]entities.PublishedStrategyScript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllPublished indicates an expected call of FindAllPublished.
func (mr *MockIStrategyScriptRepositoryMockRecorder) FindAllPublished(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllPublished", reflect.TypeOf((*MockIStrategyScriptRepository)(nil).FindAllPublished), executionContext)
}

// FindOne mocks base method.
func (m *MockIStrategyScriptRepository) FindOne(executionContext context.Context, id uint) (entities.StrategyScript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.StrategyScript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIStrategyScriptRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIStrategyScriptRepository)(nil).FindOne), executionContext, id)
}

// Save mocks base method.
func (m *MockIStrategyScriptRepository) Save(executionContext context.Context, strategyScript entities.StrategyScript) (entities.StrategyScript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, strategyScript)
	ret0, _ := ret[0].(entities.StrategyScript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIStrategyScriptRepositoryMockRecorder) Save(executionContext, strategyScript any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIStrategyScriptRepository)(nil).Save), executionContext, strategyScript)
}

// Update mocks base method.
func (m *MockIStrategyScriptRepository) Update(executionContext context.Context, strategyScript entities.StrategyScript) (entities.StrategyScript, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", executionContext, strategyScript)
	ret0, _ := ret[0].(entities.StrategyScript)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIStrategyScriptRepositoryMockRecorder) Update(executionContext, strategyScript any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIStrategyScriptRepository)(nil).Update), executionContext, strategyScript)
}
