// Code generated by MockGen. DO NOT EDIT.
// Source: i_refresh_token_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_refresh_token_proxy.go -destination=mocks/mock_i_refresh_token_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIRefreshTokenProxy is a mock of IRefreshTokenProxy interface.
type MockIRefreshTokenProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIRefreshTokenProxyMockRecorder
	isgomock struct{}
}

// MockIRefreshTokenProxyMockRecorder is the mock recorder for MockIRefreshTokenProxy.
type MockIRefreshTokenProxyMockRecorder struct {
	mock *MockIRefreshTokenProxy
}

// NewMockIRefreshTokenProxy creates a new mock instance.
func NewMockIRefreshTokenProxy(ctrl *gomock.Controller) *MockIRefreshTokenProxy {
	mock := &MockIRefreshTokenProxy{ctrl: ctrl}
	mock.recorder = &MockIRefreshTokenProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRefreshTokenProxy) EXPECT() *MockIRefreshTokenProxyMockRecorder {
	return m.recorder
}

// DigestOf mocks base method.
func (m *MockIRefreshTokenProxy) DigestOf(refreshToken string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DigestOf", refreshToken)
	ret0, _ := ret[0].(string)
	return ret0
}

// DigestOf indicates an expected call of DigestOf.
func (mr *MockIRefreshTokenProxyMockRecorder) DigestOf(refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DigestOf", reflect.TypeOf((*MockIRefreshTokenProxy)(nil).DigestOf), refreshToken)
}

// Mint mocks base method.
func (m *MockIRefreshTokenProxy) Mint() (vo.RefreshTokenVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mint")
	ret0, _ := ret[0].(vo.RefreshTokenVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mint indicates an expected call of Mint.
func (mr *MockIRefreshTokenProxyMockRecorder) Mint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mint", reflect.TypeOf((*MockIRefreshTokenProxy)(nil).Mint))
}
