// Code generated by MockGen. DO NOT EDIT.
// Source: i_k_candle_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_k_candle_repository.go -destination=mocks/mock_i_k_candle_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domains "github.com/CodeMachine0121/go-trading/internal/domain/models/domains"
	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIKCandleRepository is a mock of IKCandleRepository interface.
type MockIKCandleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIKCandleRepositoryMockRecorder
	isgomock struct{}
}

// MockIKCandleRepositoryMockRecorder is the mock recorder for MockIKCandleRepository.
type MockIKCandleRepositoryMockRecorder struct {
	mock *MockIKCandleRepository
}

// NewMockIKCandleRepository creates a new mock instance.
func NewMockIKCandleRepository(ctrl *gomock.Controller) *MockIKCandleRepository {
	mock := &MockIKCandleRepository{ctrl: ctrl}
	mock.recorder = &MockIKCandleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIKCandleRepository) EXPECT() *MockIKCandleRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIKCandleRepository) Delete(executionContext context.Context, symbol string, openTime time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", executionContext, symbol, openTime)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIKCandleRepositoryMockRecorder) Delete(executionContext, symbol, openTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIKCandleRepository)(nil).Delete), executionContext, symbol, openTime)
}

// FindDistinctSymbols mocks base method.
func (m *MockIKCandleRepository) FindDistinctSymbols(executionContext context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDistinctSymbols", executionContext)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDistinctSymbols indicates an expected call of FindDistinctSymbols.
func (mr *MockIKCandleRepositoryMockRecorder) FindDistinctSymbols(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDistinctSymbols", reflect.TypeOf((*MockIKCandleRepository)(nil).FindDistinctSymbols), executionContext)
}

// FindInRange mocks base method.
func (m *MockIKCandleRepository) FindInRange(executionContext context.Context, query domains.KCandleQueryDomain, limit int) ([]entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInRange", executionContext, query, limit)
	ret0, _ := ret[0].([]entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInRange indicates an expected call of FindInRange.
func (mr *MockIKCandleRepositoryMockRecorder) FindInRange(executionContext, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInRange", reflect.TypeOf((*MockIKCandleRepository)(nil).FindInRange), executionContext, query, limit)
}

// FindLatest mocks base method.
func (m *MockIKCandleRepository) FindLatest(executionContext context.Context, symbol string, limit int) ([]entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatest", executionContext, symbol, limit)
	ret0, _ := ret[0].([]entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatest indicates an expected call of FindLatest.
func (mr *MockIKCandleRepositoryMockRecorder) FindLatest(executionContext, symbol, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatest", reflect.TypeOf((*MockIKCandleRepository)(nil).FindLatest), executionContext, symbol, limit)
}

// FindLatestBefore mocks base method.
func (m *MockIKCandleRepository) FindLatestBefore(executionContext context.Context, symbol string, cutoffTime time.Time, limit int) ([]entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestBefore", executionContext, symbol, cutoffTime, limit)
	ret0, _ := ret[0].([]entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestBefore indicates an expected call of FindLatestBefore.
func (mr *MockIKCandleRepositoryMockRecorder) FindLatestBefore(executionContext, symbol, cutoffTime, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestBefore", reflect.TypeOf((*MockIKCandleRepository)(nil).FindLatestBefore), executionContext, symbol, cutoffTime, limit)
}

// FindOne mocks base method.
func (m *MockIKCandleRepository) FindOne(executionContext context.Context, symbol string, openTime time.Time) (entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, symbol, openTime)
	ret0, _ := ret[0].(entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIKCandleRepositoryMockRecorder) FindOne(executionContext, symbol, openTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIKCandleRepository)(nil).FindOne), executionContext, symbol, openTime)
}

// Save mocks base method.
func (m *MockIKCandleRepository) Save(executionContext context.Context, kCandle entities.KCandle) (entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, kCandle)
	ret0, _ := ret[0].(entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIKCandleRepositoryMockRecorder) Save(executionContext, kCandle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIKCandleRepository)(nil).Save), executionContext, kCandle)
}

// Update mocks base method.
func (m *MockIKCandleRepository) Update(executionContext context.Context, kCandle entities.KCandle) (entities.KCandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", executionContext, kCandle)
	ret0, _ := ret[0].(entities.KCandle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIKCandleRepositoryMockRecorder) Update(executionContext, kCandle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIKCandleRepository)(nil).Update), executionContext, kCandle)
}
