// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_symbol_lookup_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_symbol_lookup_proxy.go -destination=mocks/mock_i_contract_symbol_lookup_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractSymbolLookupProxy is a mock of IContractSymbolLookupProxy interface.
type MockIContractSymbolLookupProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIContractSymbolLookupProxyMockRecorder
	isgomock struct{}
}

// MockIContractSymbolLookupProxyMockRecorder is the mock recorder for MockIContractSymbolLookupProxy.
type MockIContractSymbolLookupProxyMockRecorder struct {
	mock *MockIContractSymbolLookupProxy
}

// NewMockIContractSymbolLookupProxy creates a new mock instance.
func NewMockIContractSymbolLookupProxy(ctrl *gomock.Controller) *MockIContractSymbolLookupProxy {
	mock := &MockIContractSymbolLookupProxy{ctrl: ctrl}
	mock.recorder = &MockIContractSymbolLookupProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractSymbolLookupProxy) EXPECT() *MockIContractSymbolLookupProxyMockRecorder {
	return m.recorder
}

// FetchTradingSpecifications mocks base method.
func (m *MockIContractSymbolLookupProxy) FetchTradingSpecifications(executionContext context.Context) ([]vo.ContractTradingSpecificationVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTradingSpecifications", executionContext)
	ret0, _ := ret[0].([]vo.ContractTradingSpecificationVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTradingSpecifications indicates an expected call of FetchTradingSpecifications.
func (mr *MockIContractSymbolLookupProxyMockRecorder) FetchTradingSpecifications(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTradingSpecifications", reflect.TypeOf((*MockIContractSymbolLookupProxy)(nil).FetchTradingSpecifications), executionContext)
}

// LookUpSymbol mocks base method.
func (m *MockIContractSymbolLookupProxy) LookUpSymbol(executionContext context.Context, symbol string) (vo.ContractSymbolListingVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookUpSymbol", executionContext, symbol)
	ret0, _ := ret[0].(vo.ContractSymbolListingVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookUpSymbol indicates an expected call of LookUpSymbol.
func (mr *MockIContractSymbolLookupProxyMockRecorder) LookUpSymbol(executionContext, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookUpSymbol", reflect.TypeOf((*MockIContractSymbolLookupProxy)(nil).LookUpSymbol), executionContext, symbol)
}
