// Code generated by MockGen. DO NOT EDIT.
// Source: i_opaque_identifier_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_opaque_identifier_proxy.go -destination=mocks/mock_i_opaque_identifier_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIOpaqueIdentifierProxy is a mock of IOpaqueIdentifierProxy interface.
type MockIOpaqueIdentifierProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIOpaqueIdentifierProxyMockRecorder
	isgomock struct{}
}

// MockIOpaqueIdentifierProxyMockRecorder is the mock recorder for MockIOpaqueIdentifierProxy.
type MockIOpaqueIdentifierProxyMockRecorder struct {
	mock *MockIOpaqueIdentifierProxy
}

// NewMockIOpaqueIdentifierProxy creates a new mock instance.
func NewMockIOpaqueIdentifierProxy(ctrl *gomock.Controller) *MockIOpaqueIdentifierProxy {
	mock := &MockIOpaqueIdentifierProxy{ctrl: ctrl}
	mock.recorder = &MockIOpaqueIdentifierProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOpaqueIdentifierProxy) EXPECT() *MockIOpaqueIdentifierProxyMockRecorder {
	return m.recorder
}

// DigestOf mocks base method.
func (m *MockIOpaqueIdentifierProxy) DigestOf(identifier string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DigestOf", identifier)
	ret0, _ := ret[0].(string)
	return ret0
}

// DigestOf indicates an expected call of DigestOf.
func (mr *MockIOpaqueIdentifierProxyMockRecorder) DigestOf(identifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DigestOf", reflect.TypeOf((*MockIOpaqueIdentifierProxy)(nil).DigestOf), identifier)
}

// Mint mocks base method.
func (m *MockIOpaqueIdentifierProxy) Mint() (vo.OpaqueIdentifierVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mint")
	ret0, _ := ret[0].(vo.OpaqueIdentifierVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mint indicates an expected call of Mint.
func (mr *MockIOpaqueIdentifierProxyMockRecorder) Mint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mint", reflect.TypeOf((*MockIOpaqueIdentifierProxy)(nil).Mint))
}
