// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_position_statistic_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_position_statistic_proxy.go -destination=mocks/mock_i_contract_position_statistic_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractPositionStatisticProxy is a mock of IContractPositionStatisticProxy interface.
type MockIContractPositionStatisticProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIContractPositionStatisticProxyMockRecorder
	isgomock struct{}
}

// MockIContractPositionStatisticProxyMockRecorder is the mock recorder for MockIContractPositionStatisticProxy.
type MockIContractPositionStatisticProxyMockRecorder struct {
	mock *MockIContractPositionStatisticProxy
}

// NewMockIContractPositionStatisticProxy creates a new mock instance.
func NewMockIContractPositionStatisticProxy(ctrl *gomock.Controller) *MockIContractPositionStatisticProxy {
	mock := &MockIContractPositionStatisticProxy{ctrl: ctrl}
	mock.recorder = &MockIContractPositionStatisticProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractPositionStatisticProxy) EXPECT() *MockIContractPositionStatisticProxyMockRecorder {
	return m.recorder
}

// FetchPositionStatistics mocks base method.
func (m *MockIContractPositionStatisticProxy) FetchPositionStatistics(executionContext context.Context, symbol string, startTime, endTime time.Time) ([]vo.ContractPositionStatisticVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPositionStatistics", executionContext, symbol, startTime, endTime)
	ret0, _ := ret[0].([]vo.ContractPositionStatisticVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPositionStatistics indicates an expected call of FetchPositionStatistics.
func (mr *MockIContractPositionStatisticProxyMockRecorder) FetchPositionStatistics(executionContext, symbol, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPositionStatistics", reflect.TypeOf((*MockIContractPositionStatisticProxy)(nil).FetchPositionStatistics), executionContext, symbol, startTime, endTime)
}
