// Code generated by MockGen. DO NOT EDIT.
// Source: i_replica_heartbeat_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_replica_heartbeat_repository.go -destination=mocks/mock_i_replica_heartbeat_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIReplicaHeartbeatRepository is a mock of IReplicaHeartbeatRepository interface.
type MockIReplicaHeartbeatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIReplicaHeartbeatRepositoryMockRecorder
	isgomock struct{}
}

// MockIReplicaHeartbeatRepositoryMockRecorder is the mock recorder for MockIReplicaHeartbeatRepository.
type MockIReplicaHeartbeatRepositoryMockRecorder struct {
	mock *MockIReplicaHeartbeatRepository
}

// NewMockIReplicaHeartbeatRepository creates a new mock instance.
func NewMockIReplicaHeartbeatRepository(ctrl *gomock.Controller) *MockIReplicaHeartbeatRepository {
	mock := &MockIReplicaHeartbeatRepository{ctrl: ctrl}
	mock.recorder = &MockIReplicaHeartbeatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReplicaHeartbeatRepository) EXPECT() *MockIReplicaHeartbeatRepositoryMockRecorder {
	return m.recorder
}

// Beat mocks base method.
func (m *MockIReplicaHeartbeatRepository) Beat(executionContext context.Context, replicaName string, seenAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Beat", executionContext, replicaName, seenAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Beat indicates an expected call of Beat.
func (mr *MockIReplicaHeartbeatRepositoryMockRecorder) Beat(executionContext, replicaName, seenAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Beat", reflect.TypeOf((*MockIReplicaHeartbeatRepository)(nil).Beat), executionContext, replicaName, seenAt)
}

// FindSeenSince mocks base method.
func (m *MockIReplicaHeartbeatRepository) FindSeenSince(executionContext context.Context, since time.Time) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSeenSince", executionContext, since)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSeenSince indicates an expected call of FindSeenSince.
func (mr *MockIReplicaHeartbeatRepositoryMockRecorder) FindSeenSince(executionContext, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSeenSince", reflect.TypeOf((*MockIReplicaHeartbeatRepository)(nil).FindSeenSince), executionContext, since)
}
