// Code generated by MockGen. DO NOT EDIT.
// Source: i_published_strategy_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_published_strategy_repository.go -destination=mocks/mock_i_published_strategy_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIPublishedStrategyRepository is a mock of IPublishedStrategyRepository interface.
type MockIPublishedStrategyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPublishedStrategyRepositoryMockRecorder
	isgomock struct{}
}

// MockIPublishedStrategyRepositoryMockRecorder is the mock recorder for MockIPublishedStrategyRepository.
type MockIPublishedStrategyRepositoryMockRecorder struct {
	mock *MockIPublishedStrategyRepository
}

// NewMockIPublishedStrategyRepository creates a new mock instance.
func NewMockIPublishedStrategyRepository(ctrl *gomock.Controller) *MockIPublishedStrategyRepository {
	mock := &MockIPublishedStrategyRepository{ctrl: ctrl}
	mock.recorder = &MockIPublishedStrategyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPublishedStrategyRepository) EXPECT() *MockIPublishedStrategyRepositoryMockRecorder {
	return m.recorder
}

// FindOne mocks base method.
func (m *MockIPublishedStrategyRepository) FindOne(executionContext context.Context, strategyID uint) (entities.PublishedStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, strategyID)
	ret0, _ := ret[0].(entities.PublishedStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIPublishedStrategyRepositoryMockRecorder) FindOne(executionContext, strategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIPublishedStrategyRepository)(nil).FindOne), executionContext, strategyID)
}

// Publish mocks base method.
func (m *MockIPublishedStrategyRepository) Publish(executionContext context.Context, strategyID uint, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", executionContext, strategyID, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockIPublishedStrategyRepositoryMockRecorder) Publish(executionContext, strategyID, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIPublishedStrategyRepository)(nil).Publish), executionContext, strategyID, publishedAt)
}

// Withdraw mocks base method.
func (m *MockIPublishedStrategyRepository) Withdraw(executionContext context.Context, strategyID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", executionContext, strategyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockIPublishedStrategyRepositoryMockRecorder) Withdraw(executionContext, strategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockIPublishedStrategyRepository)(nil).Withdraw), executionContext, strategyID)
}
