// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_maintenance_margin_tier_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_maintenance_margin_tier_repository.go -destination=mocks/mock_i_contract_maintenance_margin_tier_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractMaintenanceMarginTierRepository is a mock of IContractMaintenanceMarginTierRepository interface.
type MockIContractMaintenanceMarginTierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContractMaintenanceMarginTierRepositoryMockRecorder
	isgomock struct{}
}

// MockIContractMaintenanceMarginTierRepositoryMockRecorder is the mock recorder for MockIContractMaintenanceMarginTierRepository.
type MockIContractMaintenanceMarginTierRepositoryMockRecorder struct {
	mock *MockIContractMaintenanceMarginTierRepository
}

// NewMockIContractMaintenanceMarginTierRepository creates a new mock instance.
func NewMockIContractMaintenanceMarginTierRepository(ctrl *gomock.Controller) *MockIContractMaintenanceMarginTierRepository {
	mock := &MockIContractMaintenanceMarginTierRepository{ctrl: ctrl}
	mock.recorder = &MockIContractMaintenanceMarginTierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractMaintenanceMarginTierRepository) EXPECT() *MockIContractMaintenanceMarginTierRepositoryMockRecorder {
	return m.recorder
}

// FindBySymbol mocks base method.
func (m *MockIContractMaintenanceMarginTierRepository) FindBySymbol(executionContext context.Context, symbol string) ([]entities.ContractMaintenanceMarginTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySymbol", executionContext, symbol)
	ret0, _ := ret[0].([]entities.ContractMaintenanceMarginTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySymbol indicates an expected call of FindBySymbol.
func (mr *MockIContractMaintenanceMarginTierRepositoryMockRecorder) FindBySymbol(executionContext, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySymbol", reflect.TypeOf((*MockIContractMaintenanceMarginTierRepository)(nil).FindBySymbol), executionContext, symbol)
}

// ReplaceLadders mocks base method.
func (m *MockIContractMaintenanceMarginTierRepository) ReplaceLadders(executionContext context.Context, laddersBySymbol map[string][]entities.ContractMaintenanceMarginTier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceLadders", executionContext, laddersBySymbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceLadders indicates an expected call of ReplaceLadders.
func (mr *MockIContractMaintenanceMarginTierRepositoryMockRecorder) ReplaceLadders(executionContext, laddersBySymbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceLadders", reflect.TypeOf((*MockIContractMaintenanceMarginTierRepository)(nil).ReplaceLadders), executionContext, laddersBySymbol)
}
