// Code generated by MockGen. DO NOT EDIT.
// Source: i_live_k_candle_snapshot_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_live_k_candle_snapshot_repository.go -destination=mocks/mock_i_live_k_candle_snapshot_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockILiveKCandleSnapshotRepository is a mock of ILiveKCandleSnapshotRepository interface.
type MockILiveKCandleSnapshotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockILiveKCandleSnapshotRepositoryMockRecorder
	isgomock struct{}
}

// MockILiveKCandleSnapshotRepositoryMockRecorder is the mock recorder for MockILiveKCandleSnapshotRepository.
type MockILiveKCandleSnapshotRepositoryMockRecorder struct {
	mock *MockILiveKCandleSnapshotRepository
}

// NewMockILiveKCandleSnapshotRepository creates a new mock instance.
func NewMockILiveKCandleSnapshotRepository(ctrl *gomock.Controller) *MockILiveKCandleSnapshotRepository {
	mock := &MockILiveKCandleSnapshotRepository{ctrl: ctrl}
	mock.recorder = &MockILiveKCandleSnapshotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILiveKCandleSnapshotRepository) EXPECT() *MockILiveKCandleSnapshotRepositoryMockRecorder {
	return m.recorder
}

// FindBySymbols mocks base method.
func (m *MockILiveKCandleSnapshotRepository) FindBySymbols(executionContext context.Context, symbols []string) ([]entities.LiveKCandleSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySymbols", executionContext, symbols)
	ret0, _ := ret[0].([]entities.LiveKCandleSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySymbols indicates an expected call of FindBySymbols.
func (mr *MockILiveKCandleSnapshotRepositoryMockRecorder) FindBySymbols(executionContext, symbols any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySymbols", reflect.TypeOf((*MockILiveKCandleSnapshotRepository)(nil).FindBySymbols), executionContext, symbols)
}

// Save mocks base method.
func (m *MockILiveKCandleSnapshotRepository) Save(executionContext context.Context, snapshot entities.LiveKCandleSnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, snapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockILiveKCandleSnapshotRepositoryMockRecorder) Save(executionContext, snapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockILiveKCandleSnapshotRepository)(nil).Save), executionContext, snapshot)
}
