// Code generated by MockGen. DO NOT EDIT.
// Source: i_strategy_bot_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_strategy_bot_repository.go -destination=mocks/mock_i_strategy_bot_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIStrategyBotRepository is a mock of IStrategyBotRepository interface.
type MockIStrategyBotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyBotRepositoryMockRecorder
	isgomock struct{}
}

// MockIStrategyBotRepositoryMockRecorder is the mock recorder for MockIStrategyBotRepository.
type MockIStrategyBotRepositoryMockRecorder struct {
	mock *MockIStrategyBotRepository
}

// NewMockIStrategyBotRepository creates a new mock instance.
func NewMockIStrategyBotRepository(ctrl *gomock.Controller) *MockIStrategyBotRepository {
	mock := &MockIStrategyBotRepository{ctrl: ctrl}
	mock.recorder = &MockIStrategyBotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategyBotRepository) EXPECT() *MockIStrategyBotRepositoryMockRecorder {
	return m.recorder
}

// ClaimDue mocks base method.
func (m *MockIStrategyBotRepository) ClaimDue(executionContext context.Context, moment time.Time, limit int, claimant string, claimedUntil time.Time) ([]entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimDue", executionContext, moment, limit, claimant, claimedUntil)
	ret0, _ := ret[0].([]entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimDue indicates an expected call of ClaimDue.
func (mr *MockIStrategyBotRepositoryMockRecorder) ClaimDue(executionContext, moment, limit, claimant, claimedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimDue", reflect.TypeOf((*MockIStrategyBotRepository)(nil).ClaimDue), executionContext, moment, limit, claimant, claimedUntil)
}

// ClaimOne mocks base method.
func (m *MockIStrategyBotRepository) ClaimOne(executionContext context.Context, id uint, claimant string, moment, claimedUntil time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimOne", executionContext, id, claimant, moment, claimedUntil)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimOne indicates an expected call of ClaimOne.
func (mr *MockIStrategyBotRepositoryMockRecorder) ClaimOne(executionContext, id, claimant, moment, claimedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimOne", reflect.TypeOf((*MockIStrategyBotRepository)(nil).ClaimOne), executionContext, id, claimant, moment, claimedUntil)
}

// CountRunningByOwner mocks base method.
func (m *MockIStrategyBotRepository) CountRunningByOwner(executionContext context.Context, ownerID uint) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountRunningByOwner", executionContext, ownerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountRunningByOwner indicates an expected call of CountRunningByOwner.
func (mr *MockIStrategyBotRepositoryMockRecorder) CountRunningByOwner(executionContext, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountRunningByOwner", reflect.TypeOf((*MockIStrategyBotRepository)(nil).CountRunningByOwner), executionContext, ownerID)
}

// Delete mocks base method.
func (m *MockIStrategyBotRepository) Delete(executionContext context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", executionContext, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIStrategyBotRepositoryMockRecorder) Delete(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIStrategyBotRepository)(nil).Delete), executionContext, id)
}

// DisableAutoOrder mocks base method.
func (m *MockIStrategyBotRepository) DisableAutoOrder(executionContext context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableAutoOrder", executionContext, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableAutoOrder indicates an expected call of DisableAutoOrder.
func (mr *MockIStrategyBotRepositoryMockRecorder) DisableAutoOrder(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableAutoOrder", reflect.TypeOf((*MockIStrategyBotRepository)(nil).DisableAutoOrder), executionContext, id)
}

// DisableAutoOrderByOwner mocks base method.
func (m *MockIStrategyBotRepository) DisableAutoOrderByOwner(executionContext context.Context, ownerID uint, marketDataKinds []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableAutoOrderByOwner", executionContext, ownerID, marketDataKinds)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisableAutoOrderByOwner indicates an expected call of DisableAutoOrderByOwner.
func (mr *MockIStrategyBotRepositoryMockRecorder) DisableAutoOrderByOwner(executionContext, ownerID, marketDataKinds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableAutoOrderByOwner", reflect.TypeOf((*MockIStrategyBotRepository)(nil).DisableAutoOrderByOwner), executionContext, ownerID, marketDataKinds)
}

// EnableAutoOrder mocks base method.
func (m *MockIStrategyBotRepository) EnableAutoOrder(executionContext context.Context, id, ownerID uint, binanceTradingKeyConfiguredAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableAutoOrder", executionContext, id, ownerID, binanceTradingKeyConfiguredAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableAutoOrder indicates an expected call of EnableAutoOrder.
func (mr *MockIStrategyBotRepositoryMockRecorder) EnableAutoOrder(executionContext, id, ownerID, binanceTradingKeyConfiguredAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableAutoOrder", reflect.TypeOf((*MockIStrategyBotRepository)(nil).EnableAutoOrder), executionContext, id, ownerID, binanceTradingKeyConfiguredAt)
}

// FindAllByOwner mocks base method.
func (m *MockIStrategyBotRepository) FindAllByOwner(executionContext context.Context, ownerID uint) ([]entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByOwner", executionContext, ownerID)
	ret0, _ := ret[0].([]entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByOwner indicates an expected call of FindAllByOwner.
func (mr *MockIStrategyBotRepositoryMockRecorder) FindAllByOwner(executionContext, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByOwner", reflect.TypeOf((*MockIStrategyBotRepository)(nil).FindAllByOwner), executionContext, ownerID)
}

// FindAllByStrategyScript mocks base method.
func (m *MockIStrategyBotRepository) FindAllByStrategyScript(executionContext context.Context, strategyScriptID uint) ([]entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByStrategyScript", executionContext, strategyScriptID)
	ret0, _ := ret[0].([]entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByStrategyScript indicates an expected call of FindAllByStrategyScript.
func (mr *MockIStrategyBotRepositoryMockRecorder) FindAllByStrategyScript(executionContext, strategyScriptID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByStrategyScript", reflect.TypeOf((*MockIStrategyBotRepository)(nil).FindAllByStrategyScript), executionContext, strategyScriptID)
}

// FindAllByTradingStrategy mocks base method.
func (m *MockIStrategyBotRepository) FindAllByTradingStrategy(executionContext context.Context, tradingStrategyID uint) ([]entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByTradingStrategy", executionContext, tradingStrategyID)
	ret0, _ := ret[0].([]entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByTradingStrategy indicates an expected call of FindAllByTradingStrategy.
func (mr *MockIStrategyBotRepositoryMockRecorder) FindAllByTradingStrategy(executionContext, tradingStrategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByTradingStrategy", reflect.TypeOf((*MockIStrategyBotRepository)(nil).FindAllByTradingStrategy), executionContext, tradingStrategyID)
}

// FindOne mocks base method.
func (m *MockIStrategyBotRepository) FindOne(executionContext context.Context, id uint) (entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIStrategyBotRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIStrategyBotRepository)(nil).FindOne), executionContext, id)
}

// FindOneLocked mocks base method.
func (m *MockIStrategyBotRepository) FindOneLocked(executionContext context.Context, id uint) (entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneLocked", executionContext, id)
	ret0, _ := ret[0].(entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneLocked indicates an expected call of FindOneLocked.
func (mr *MockIStrategyBotRepositoryMockRecorder) FindOneLocked(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneLocked", reflect.TypeOf((*MockIStrategyBotRepository)(nil).FindOneLocked), executionContext, id)
}

// ForgetSentSignal mocks base method.
func (m *MockIStrategyBotRepository) ForgetSentSignal(executionContext context.Context, id uint, roundDueAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgetSentSignal", executionContext, id, roundDueAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgetSentSignal indicates an expected call of ForgetSentSignal.
func (mr *MockIStrategyBotRepositoryMockRecorder) ForgetSentSignal(executionContext, id, roundDueAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgetSentSignal", reflect.TypeOf((*MockIStrategyBotRepository)(nil).ForgetSentSignal), executionContext, id, roundDueAt)
}

// ReleaseRoundClaim mocks base method.
func (m *MockIStrategyBotRepository) ReleaseRoundClaim(executionContext context.Context, id uint, claimant string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseRoundClaim", executionContext, id, claimant)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseRoundClaim indicates an expected call of ReleaseRoundClaim.
func (mr *MockIStrategyBotRepositoryMockRecorder) ReleaseRoundClaim(executionContext, id, claimant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseRoundClaim", reflect.TypeOf((*MockIStrategyBotRepository)(nil).ReleaseRoundClaim), executionContext, id, claimant)
}

// Save mocks base method.
func (m *MockIStrategyBotRepository) Save(executionContext context.Context, bot entities.StrategyBot) (entities.StrategyBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, bot)
	ret0, _ := ret[0].(entities.StrategyBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIStrategyBotRepositoryMockRecorder) Save(executionContext, bot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIStrategyBotRepository)(nil).Save), executionContext, bot)
}

// UpdateAutoOrderPosition mocks base method.
func (m *MockIStrategyBotRepository) UpdateAutoOrderPosition(executionContext context.Context, id uint, position vo.AutoOrderPositionVo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutoOrderPosition", executionContext, id, position)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAutoOrderPosition indicates an expected call of UpdateAutoOrderPosition.
func (mr *MockIStrategyBotRepositoryMockRecorder) UpdateAutoOrderPosition(executionContext, id, position any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutoOrderPosition", reflect.TypeOf((*MockIStrategyBotRepository)(nil).UpdateAutoOrderPosition), executionContext, id, position)
}

// UpdateRunState mocks base method.
func (m *MockIStrategyBotRepository) UpdateRunState(executionContext context.Context, bot entities.StrategyBot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRunState", executionContext, bot)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRunState indicates an expected call of UpdateRunState.
func (mr *MockIStrategyBotRepositoryMockRecorder) UpdateRunState(executionContext, bot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRunState", reflect.TypeOf((*MockIStrategyBotRepository)(nil).UpdateRunState), executionContext, bot)
}
