// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_indicator_script_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_indicator_script_proxy.go -destination=mocks/mock_i_contract_indicator_script_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domains "github.com/CodeMachine0121/go-trading/internal/domain/models/domains"
	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractIndicatorScriptProxy is a mock of IContractIndicatorScriptProxy interface.
type MockIContractIndicatorScriptProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIContractIndicatorScriptProxyMockRecorder
	isgomock struct{}
}

// MockIContractIndicatorScriptProxyMockRecorder is the mock recorder for MockIContractIndicatorScriptProxy.
type MockIContractIndicatorScriptProxyMockRecorder struct {
	mock *MockIContractIndicatorScriptProxy
}

// NewMockIContractIndicatorScriptProxy creates a new mock instance.
func NewMockIContractIndicatorScriptProxy(ctrl *gomock.Controller) *MockIContractIndicatorScriptProxy {
	mock := &MockIContractIndicatorScriptProxy{ctrl: ctrl}
	mock.recorder = &MockIContractIndicatorScriptProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractIndicatorScriptProxy) EXPECT() *MockIContractIndicatorScriptProxyMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockIContractIndicatorScriptProxy) Execute(executionContext context.Context, script string, resultType domains.IndicatorResultTypeDomain, contractKCandles []vo.ContractKCandleVo, parameters domains.StrategyScriptParametersDomain) (map[string]vo.IndicatorValueVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", executionContext, script, resultType, contractKCandles, parameters)
	ret0, _ := ret[0].(map[string]vo.IndicatorValueVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockIContractIndicatorScriptProxyMockRecorder) Execute(executionContext, script, resultType, contractKCandles, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockIContractIndicatorScriptProxy)(nil).Execute), executionContext, script, resultType, contractKCandles, parameters)
}

// ExecuteForEachCandle mocks base method.
func (m *MockIContractIndicatorScriptProxy) ExecuteForEachCandle(executionContext context.Context, script string, resultType domains.IndicatorResultTypeDomain, contractKCandles []vo.ContractKCandleVo, parameters domains.StrategyScriptParametersDomain) ([]map[string]vo.IndicatorValueVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteForEachCandle", executionContext, script, resultType, contractKCandles, parameters)
	ret0, _ := ret[0].([]map[string]vo.IndicatorValueVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteForEachCandle indicates an expected call of ExecuteForEachCandle.
func (mr *MockIContractIndicatorScriptProxyMockRecorder) ExecuteForEachCandle(executionContext, script, resultType, contractKCandles, parameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteForEachCandle", reflect.TypeOf((*MockIContractIndicatorScriptProxy)(nil).ExecuteForEachCandle), executionContext, script, resultType, contractKCandles, parameters)
}
