// Code generated by MockGen. DO NOT EDIT.
// Source: i_assistant_revision_applier.go
//
// Generated by this command:
//
//	mockgen -source=i_assistant_revision_applier.go -destination=mocks/mock_i_assistant_revision_applier.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/CodeMachine0121/go-trading/internal/domain/models/dto"
	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIAssistantRevisionApplier is a mock of IAssistantRevisionApplier interface.
type MockIAssistantRevisionApplier struct {
	ctrl     *gomock.Controller
	recorder *MockIAssistantRevisionApplierMockRecorder
	isgomock struct{}
}

// MockIAssistantRevisionApplierMockRecorder is the mock recorder for MockIAssistantRevisionApplier.
type MockIAssistantRevisionApplierMockRecorder struct {
	mock *MockIAssistantRevisionApplier
}

// NewMockIAssistantRevisionApplier creates a new mock instance.
func NewMockIAssistantRevisionApplier(ctrl *gomock.Controller) *MockIAssistantRevisionApplier {
	mock := &MockIAssistantRevisionApplier{ctrl: ctrl}
	mock.recorder = &MockIAssistantRevisionApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssistantRevisionApplier) EXPECT() *MockIAssistantRevisionApplierMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockIAssistantRevisionApplier) Apply(executionContext context.Context, viewerID uint, content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", executionContext, viewerID, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockIAssistantRevisionApplierMockRecorder) Apply(executionContext, viewerID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockIAssistantRevisionApplier)(nil).Apply), executionContext, viewerID, content)
}

// Inspect mocks base method.
func (m *MockIAssistantRevisionApplier) Inspect(executionContext context.Context, viewerID uint, content string) (dto.RewriteTargetDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inspect", executionContext, viewerID, content)
	ret0, _ := ret[0].(dto.RewriteTargetDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Inspect indicates an expected call of Inspect.
func (mr *MockIAssistantRevisionApplierMockRecorder) Inspect(executionContext, viewerID, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inspect", reflect.TypeOf((*MockIAssistantRevisionApplier)(nil).Inspect), executionContext, viewerID, content)
}

// SubjectKind mocks base method.
func (m *MockIAssistantRevisionApplier) SubjectKind() vo.AssistantRevisionSubjectKindVo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubjectKind")
	ret0, _ := ret[0].(vo.AssistantRevisionSubjectKindVo)
	return ret0
}

// SubjectKind indicates an expected call of SubjectKind.
func (mr *MockIAssistantRevisionApplierMockRecorder) SubjectKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubjectKind", reflect.TypeOf((*MockIAssistantRevisionApplier)(nil).SubjectKind))
}
