// Code generated by MockGen. DO NOT EDIT.
// Source: i_telegram_delivery_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_telegram_delivery_repository.go -destination=mocks/mock_i_telegram_delivery_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockITelegramDeliveryRepository is a mock of ITelegramDeliveryRepository interface.
type MockITelegramDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITelegramDeliveryRepositoryMockRecorder
	isgomock struct{}
}

// MockITelegramDeliveryRepositoryMockRecorder is the mock recorder for MockITelegramDeliveryRepository.
type MockITelegramDeliveryRepositoryMockRecorder struct {
	mock *MockITelegramDeliveryRepository
}

// NewMockITelegramDeliveryRepository creates a new mock instance.
func NewMockITelegramDeliveryRepository(ctrl *gomock.Controller) *MockITelegramDeliveryRepository {
	mock := &MockITelegramDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockITelegramDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITelegramDeliveryRepository) EXPECT() *MockITelegramDeliveryRepositoryMockRecorder {
	return m.recorder
}

// DeleteByUser mocks base method.
func (m *MockITelegramDeliveryRepository) DeleteByUser(executionContext context.Context, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUser", executionContext, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUser indicates an expected call of DeleteByUser.
func (mr *MockITelegramDeliveryRepositoryMockRecorder) DeleteByUser(executionContext, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUser", reflect.TypeOf((*MockITelegramDeliveryRepository)(nil).DeleteByUser), executionContext, userID)
}

// FindOneByUser mocks base method.
func (m *MockITelegramDeliveryRepository) FindOneByUser(executionContext context.Context, userID uint) (entities.TelegramDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUser", executionContext, userID)
	ret0, _ := ret[0].(entities.TelegramDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUser indicates an expected call of FindOneByUser.
func (mr *MockITelegramDeliveryRepositoryMockRecorder) FindOneByUser(executionContext, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUser", reflect.TypeOf((*MockITelegramDeliveryRepository)(nil).FindOneByUser), executionContext, userID)
}

// Upsert mocks base method.
func (m *MockITelegramDeliveryRepository) Upsert(executionContext context.Context, delivery entities.TelegramDelivery) (entities.TelegramDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", executionContext, delivery)
	ret0, _ := ret[0].(entities.TelegramDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockITelegramDeliveryRepositoryMockRecorder) Upsert(executionContext, delivery any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockITelegramDeliveryRepository)(nil).Upsert), executionContext, delivery)
}
