// Code generated by MockGen. DO NOT EDIT.
// Source: i_trading_strategy_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_trading_strategy_repository.go -destination=mocks/mock_i_trading_strategy_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockITradingStrategyRepository is a mock of ITradingStrategyRepository interface.
type MockITradingStrategyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITradingStrategyRepositoryMockRecorder
	isgomock struct{}
}

// MockITradingStrategyRepositoryMockRecorder is the mock recorder for MockITradingStrategyRepository.
type MockITradingStrategyRepositoryMockRecorder struct {
	mock *MockITradingStrategyRepository
}

// NewMockITradingStrategyRepository creates a new mock instance.
func NewMockITradingStrategyRepository(ctrl *gomock.Controller) *MockITradingStrategyRepository {
	mock := &MockITradingStrategyRepository{ctrl: ctrl}
	mock.recorder = &MockITradingStrategyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITradingStrategyRepository) EXPECT() *MockITradingStrategyRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockITradingStrategyRepository) Delete(executionContext context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", executionContext, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockITradingStrategyRepositoryMockRecorder) Delete(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockITradingStrategyRepository)(nil).Delete), executionContext, id)
}

// FindAllByOwner mocks base method.
func (m *MockITradingStrategyRepository) FindAllByOwner(executionContext context.Context, ownerID uint) ([]entities.TradingStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByOwner", executionContext, ownerID)
	ret0, _ := ret[0].([]entities.TradingStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByOwner indicates an expected call of FindAllByOwner.
func (mr *MockITradingStrategyRepositoryMockRecorder) FindAllByOwner(executionContext, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByOwner", reflect.TypeOf((*MockITradingStrategyRepository)(nil).FindAllByOwner), executionContext, ownerID)
}

// FindOne mocks base method.
func (m *MockITradingStrategyRepository) FindOne(executionContext context.Context, id uint) (entities.TradingStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.TradingStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockITradingStrategyRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockITradingStrategyRepository)(nil).FindOne), executionContext, id)
}

// Save mocks base method.
func (m *MockITradingStrategyRepository) Save(executionContext context.Context, tradingStrategy entities.TradingStrategy) (entities.TradingStrategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, tradingStrategy)
	ret0, _ := ret[0].(entities.TradingStrategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockITradingStrategyRepositoryMockRecorder) Save(executionContext, tradingStrategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockITradingStrategyRepository)(nil).Save), executionContext, tradingStrategy)
}
