// Code generated by MockGen. DO NOT EDIT.
// Source: i_clock_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_clock_proxy.go -destination=mocks/mock_i_clock_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIClockProxy is a mock of IClockProxy interface.
type MockIClockProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIClockProxyMockRecorder
	isgomock struct{}
}

// MockIClockProxyMockRecorder is the mock recorder for MockIClockProxy.
type MockIClockProxyMockRecorder struct {
	mock *MockIClockProxy
}

// NewMockIClockProxy creates a new mock instance.
func NewMockIClockProxy(ctrl *gomock.Controller) *MockIClockProxy {
	mock := &MockIClockProxy{ctrl: ctrl}
	mock.recorder = &MockIClockProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClockProxy) EXPECT() *MockIClockProxyMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockIClockProxy) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockIClockProxyMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockIClockProxy)(nil).Now))
}
