// Code generated by MockGen. DO NOT EDIT.
// Source: i_transaction_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_transaction_repository.go -destination=mocks/mock_i_transaction_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockITransactionRepository is a mock of ITransactionRepository interface.
type MockITransactionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITransactionRepositoryMockRecorder
	isgomock struct{}
}

// MockITransactionRepositoryMockRecorder is the mock recorder for MockITransactionRepository.
type MockITransactionRepositoryMockRecorder struct {
	mock *MockITransactionRepository
}

// NewMockITransactionRepository creates a new mock instance.
func NewMockITransactionRepository(ctrl *gomock.Controller) *MockITransactionRepository {
	mock := &MockITransactionRepository{ctrl: ctrl}
	mock.recorder = &MockITransactionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITransactionRepository) EXPECT() *MockITransactionRepositoryMockRecorder {
	return m.recorder
}

// Atomically mocks base method.
func (m *MockITransactionRepository) Atomically(executionContext context.Context, work func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Atomically", executionContext, work)
	ret0, _ := ret[0].(error)
	return ret0
}

// Atomically indicates an expected call of Atomically.
func (mr *MockITransactionRepositoryMockRecorder) Atomically(executionContext, work any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Atomically", reflect.TypeOf((*MockITransactionRepository)(nil).Atomically), executionContext, work)
}
