// Code generated by MockGen. DO NOT EDIT.
// Source: i_symbol_lookup_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_symbol_lookup_proxy.go -destination=mocks/mock_i_symbol_lookup_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockISymbolLookupProxy is a mock of ISymbolLookupProxy interface.
type MockISymbolLookupProxy struct {
	ctrl     *gomock.Controller
	recorder *MockISymbolLookupProxyMockRecorder
	isgomock struct{}
}

// MockISymbolLookupProxyMockRecorder is the mock recorder for MockISymbolLookupProxy.
type MockISymbolLookupProxyMockRecorder struct {
	mock *MockISymbolLookupProxy
}

// NewMockISymbolLookupProxy creates a new mock instance.
func NewMockISymbolLookupProxy(ctrl *gomock.Controller) *MockISymbolLookupProxy {
	mock := &MockISymbolLookupProxy{ctrl: ctrl}
	mock.recorder = &MockISymbolLookupProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISymbolLookupProxy) EXPECT() *MockISymbolLookupProxyMockRecorder {
	return m.recorder
}

// LookUpSymbol mocks base method.
func (m *MockISymbolLookupProxy) LookUpSymbol(executionContext context.Context, market vo.MarketVo, symbol string) (vo.SymbolListingVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookUpSymbol", executionContext, market, symbol)
	ret0, _ := ret[0].(vo.SymbolListingVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookUpSymbol indicates an expected call of LookUpSymbol.
func (mr *MockISymbolLookupProxyMockRecorder) LookUpSymbol(executionContext, market, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookUpSymbol", reflect.TypeOf((*MockISymbolLookupProxy)(nil).LookUpSymbol), executionContext, market, symbol)
}
