// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_auto_order_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_auto_order_repository.go -destination=mocks/mock_i_contract_auto_order_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractAutoOrderRepository is a mock of IContractAutoOrderRepository interface.
type MockIContractAutoOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContractAutoOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockIContractAutoOrderRepositoryMockRecorder is the mock recorder for MockIContractAutoOrderRepository.
type MockIContractAutoOrderRepositoryMockRecorder struct {
	mock *MockIContractAutoOrderRepository
}

// NewMockIContractAutoOrderRepository creates a new mock instance.
func NewMockIContractAutoOrderRepository(ctrl *gomock.Controller) *MockIContractAutoOrderRepository {
	mock := &MockIContractAutoOrderRepository{ctrl: ctrl}
	mock.recorder = &MockIContractAutoOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractAutoOrderRepository) EXPECT() *MockIContractAutoOrderRepositoryMockRecorder {
	return m.recorder
}

// Claim mocks base method.
func (m *MockIContractAutoOrderRepository) Claim(executionContext context.Context, id uint, claimant string, moment, claimedUntil time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", executionContext, id, claimant, moment, claimedUntil)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockIContractAutoOrderRepositoryMockRecorder) Claim(executionContext, id, claimant, moment, claimedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockIContractAutoOrderRepository)(nil).Claim), executionContext, id, claimant, moment, claimedUntil)
}

// Enqueue mocks base method.
func (m *MockIContractAutoOrderRepository) Enqueue(executionContext context.Context, contractAutoOrder entities.ContractAutoOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", executionContext, contractAutoOrder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockIContractAutoOrderRepositoryMockRecorder) Enqueue(executionContext, contractAutoOrder any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockIContractAutoOrderRepository)(nil).Enqueue), executionContext, contractAutoOrder)
}

// FindByBotRunNumbers mocks base method.
func (m *MockIContractAutoOrderRepository) FindByBotRunNumbers(executionContext context.Context, strategyBotID uint, runNumbers []int) ([]entities.ContractAutoOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBotRunNumbers", executionContext, strategyBotID, runNumbers)
	ret0, _ := ret[0].([]entities.ContractAutoOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBotRunNumbers indicates an expected call of FindByBotRunNumbers.
func (mr *MockIContractAutoOrderRepositoryMockRecorder) FindByBotRunNumbers(executionContext, strategyBotID, runNumbers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBotRunNumbers", reflect.TypeOf((*MockIContractAutoOrderRepository)(nil).FindByBotRunNumbers), executionContext, strategyBotID, runNumbers)
}

// FindDispatchCandidates mocks base method.
func (m *MockIContractAutoOrderRepository) FindDispatchCandidates(executionContext context.Context, limit int) ([]entities.ContractAutoOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDispatchCandidates", executionContext, limit)
	ret0, _ := ret[0].([]entities.ContractAutoOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDispatchCandidates indicates an expected call of FindDispatchCandidates.
func (mr *MockIContractAutoOrderRepositoryMockRecorder) FindDispatchCandidates(executionContext, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDispatchCandidates", reflect.TypeOf((*MockIContractAutoOrderRepository)(nil).FindDispatchCandidates), executionContext, limit)
}

// SaveProgress mocks base method.
func (m *MockIContractAutoOrderRepository) SaveProgress(executionContext context.Context, contractAutoOrder entities.ContractAutoOrder, claimant string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProgress", executionContext, contractAutoOrder, claimant)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveProgress indicates an expected call of SaveProgress.
func (mr *MockIContractAutoOrderRepositoryMockRecorder) SaveProgress(executionContext, contractAutoOrder, claimant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProgress", reflect.TypeOf((*MockIContractAutoOrderRepository)(nil).SaveProgress), executionContext, contractAutoOrder, claimant)
}
