// Code generated by MockGen. DO NOT EDIT.
// Source: i_pending_message_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_pending_message_repository.go -destination=mocks/mock_i_pending_message_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIPendingMessageRepository is a mock of IPendingMessageRepository interface.
type MockIPendingMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIPendingMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockIPendingMessageRepositoryMockRecorder is the mock recorder for MockIPendingMessageRepository.
type MockIPendingMessageRepositoryMockRecorder struct {
	mock *MockIPendingMessageRepository
}

// NewMockIPendingMessageRepository creates a new mock instance.
func NewMockIPendingMessageRepository(ctrl *gomock.Controller) *MockIPendingMessageRepository {
	mock := &MockIPendingMessageRepository{ctrl: ctrl}
	mock.recorder = &MockIPendingMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPendingMessageRepository) EXPECT() *MockIPendingMessageRepositoryMockRecorder {
	return m.recorder
}

// Abandon mocks base method.
func (m *MockIPendingMessageRepository) Abandon(executionContext context.Context, id uint, claimant string, reason vo.PendingMessageAbandonReasonVo, settledAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Abandon", executionContext, id, claimant, reason, settledAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Abandon indicates an expected call of Abandon.
func (mr *MockIPendingMessageRepositoryMockRecorder) Abandon(executionContext, id, claimant, reason, settledAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Abandon", reflect.TypeOf((*MockIPendingMessageRepository)(nil).Abandon), executionContext, id, claimant, reason, settledAt)
}

// Claim mocks base method.
func (m *MockIPendingMessageRepository) Claim(executionContext context.Context, id uint, claimant string, moment, claimedUntil time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", executionContext, id, claimant, moment, claimedUntil)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MockIPendingMessageRepositoryMockRecorder) Claim(executionContext, id, claimant, moment, claimedUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MockIPendingMessageRepository)(nil).Claim), executionContext, id, claimant, moment, claimedUntil)
}

// DeleteSettledBefore mocks base method.
func (m *MockIPendingMessageRepository) DeleteSettledBefore(executionContext context.Context, cutoff time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSettledBefore", executionContext, cutoff)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSettledBefore indicates an expected call of DeleteSettledBefore.
func (mr *MockIPendingMessageRepositoryMockRecorder) DeleteSettledBefore(executionContext, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSettledBefore", reflect.TypeOf((*MockIPendingMessageRepository)(nil).DeleteSettledBefore), executionContext, cutoff)
}

// Enqueue mocks base method.
func (m *MockIPendingMessageRepository) Enqueue(executionContext context.Context, pendingMessage entities.PendingMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", executionContext, pendingMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockIPendingMessageRepositoryMockRecorder) Enqueue(executionContext, pendingMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockIPendingMessageRepository)(nil).Enqueue), executionContext, pendingMessage)
}

// FindDispatchCandidates mocks base method.
func (m *MockIPendingMessageRepository) FindDispatchCandidates(executionContext context.Context, moment time.Time, limit int) ([]entities.PendingMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDispatchCandidates", executionContext, moment, limit)
	ret0, _ := ret[0].([]entities.PendingMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDispatchCandidates indicates an expected call of FindDispatchCandidates.
func (mr *MockIPendingMessageRepositoryMockRecorder) FindDispatchCandidates(executionContext, moment, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDispatchCandidates", reflect.TypeOf((*MockIPendingMessageRepository)(nil).FindDispatchCandidates), executionContext, moment, limit)
}

// MarkSent mocks base method.
func (m *MockIPendingMessageRepository) MarkSent(executionContext context.Context, id uint, claimant string, settledAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkSent", executionContext, id, claimant, settledAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkSent indicates an expected call of MarkSent.
func (mr *MockIPendingMessageRepositoryMockRecorder) MarkSent(executionContext, id, claimant, settledAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkSent", reflect.TypeOf((*MockIPendingMessageRepository)(nil).MarkSent), executionContext, id, claimant, settledAt)
}

// Reschedule mocks base method.
func (m *MockIPendingMessageRepository) Reschedule(executionContext context.Context, id uint, claimant string, attemptCount int, nextAttemptAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reschedule", executionContext, id, claimant, attemptCount, nextAttemptAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reschedule indicates an expected call of Reschedule.
func (mr *MockIPendingMessageRepositoryMockRecorder) Reschedule(executionContext, id, claimant, attemptCount, nextAttemptAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reschedule", reflect.TypeOf((*MockIPendingMessageRepository)(nil).Reschedule), executionContext, id, claimant, attemptCount, nextAttemptAt)
}
