// Code generated by MockGen. DO NOT EDIT.
// Source: i_session_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_session_repository.go -destination=mocks/mock_i_session_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockISessionRepository is a mock of ISessionRepository interface.
type MockISessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISessionRepositoryMockRecorder
	isgomock struct{}
}

// MockISessionRepositoryMockRecorder is the mock recorder for MockISessionRepository.
type MockISessionRepositoryMockRecorder struct {
	mock *MockISessionRepository
}

// NewMockISessionRepository creates a new mock instance.
func NewMockISessionRepository(ctrl *gomock.Controller) *MockISessionRepository {
	mock := &MockISessionRepository{ctrl: ctrl}
	mock.recorder = &MockISessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISessionRepository) EXPECT() *MockISessionRepositoryMockRecorder {
	return m.recorder
}

// FindOneByDigest mocks base method.
func (m *MockISessionRepository) FindOneByDigest(executionContext context.Context, refreshTokenDigest string) (entities.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByDigest", executionContext, refreshTokenDigest)
	ret0, _ := ret[0].(entities.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByDigest indicates an expected call of FindOneByDigest.
func (mr *MockISessionRepositoryMockRecorder) FindOneByDigest(executionContext, refreshTokenDigest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByDigest", reflect.TypeOf((*MockISessionRepository)(nil).FindOneByDigest), executionContext, refreshTokenDigest)
}

// RevokeChain mocks base method.
func (m *MockISessionRepository) RevokeChain(executionContext context.Context, chainID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeChain", executionContext, chainID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeChain indicates an expected call of RevokeChain.
func (mr *MockISessionRepositoryMockRecorder) RevokeChain(executionContext, chainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeChain", reflect.TypeOf((*MockISessionRepository)(nil).RevokeChain), executionContext, chainID)
}

// Rotate mocks base method.
func (m *MockISessionRepository) Rotate(executionContext context.Context, previousSessionID uint, next entities.Session) (entities.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", executionContext, previousSessionID, next)
	ret0, _ := ret[0].(entities.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockISessionRepositoryMockRecorder) Rotate(executionContext, previousSessionID, next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockISessionRepository)(nil).Rotate), executionContext, previousSessionID, next)
}

// Save mocks base method.
func (m *MockISessionRepository) Save(executionContext context.Context, session entities.Session) (entities.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, session)
	ret0, _ := ret[0].(entities.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockISessionRepositoryMockRecorder) Save(executionContext, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockISessionRepository)(nil).Save), executionContext, session)
}
