// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_trade_record_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_trade_record_repository.go -destination=mocks/mock_i_contract_trade_record_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractTradeRecordRepository is a mock of IContractTradeRecordRepository interface.
type MockIContractTradeRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContractTradeRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockIContractTradeRecordRepositoryMockRecorder is the mock recorder for MockIContractTradeRecordRepository.
type MockIContractTradeRecordRepositoryMockRecorder struct {
	mock *MockIContractTradeRecordRepository
}

// NewMockIContractTradeRecordRepository creates a new mock instance.
func NewMockIContractTradeRecordRepository(ctrl *gomock.Controller) *MockIContractTradeRecordRepository {
	mock := &MockIContractTradeRecordRepository{ctrl: ctrl}
	mock.recorder = &MockIContractTradeRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractTradeRecordRepository) EXPECT() *MockIContractTradeRecordRepositoryMockRecorder {
	return m.recorder
}

// CountByTag mocks base method.
func (m *MockIContractTradeRecordRepository) CountByTag(executionContext context.Context, tagID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTag", executionContext, tagID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTag indicates an expected call of CountByTag.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) CountByTag(executionContext, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTag", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).CountByTag), executionContext, tagID)
}

// Create mocks base method.
func (m *MockIContractTradeRecordRepository) Create(executionContext context.Context, record entities.ContractTradeRecord) (entities.ContractTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", executionContext, record)
	ret0, _ := ret[0].(entities.ContractTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) Create(executionContext, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).Create), executionContext, record)
}

// FindClosedByOwner mocks base method.
func (m *MockIContractTradeRecordRepository) FindClosedByOwner(executionContext context.Context, ownerID uint, closedSince *time.Time) ([]entities.ContractTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindClosedByOwner", executionContext, ownerID, closedSince)
	ret0, _ := ret[0].([]entities.ContractTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindClosedByOwner indicates an expected call of FindClosedByOwner.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) FindClosedByOwner(executionContext, ownerID, closedSince any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindClosedByOwner", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).FindClosedByOwner), executionContext, ownerID, closedSince)
}

// FindClosedByOwnerAndTradingStrategy mocks base method.
func (m *MockIContractTradeRecordRepository) FindClosedByOwnerAndTradingStrategy(executionContext context.Context, ownerID, tradingStrategyID uint) ([]entities.ContractTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindClosedByOwnerAndTradingStrategy", executionContext, ownerID, tradingStrategyID)
	ret0, _ := ret[0].([]entities.ContractTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindClosedByOwnerAndTradingStrategy indicates an expected call of FindClosedByOwnerAndTradingStrategy.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) FindClosedByOwnerAndTradingStrategy(executionContext, ownerID, tradingStrategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindClosedByOwnerAndTradingStrategy", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).FindClosedByOwnerAndTradingStrategy), executionContext, ownerID, tradingStrategyID)
}

// FindOne mocks base method.
func (m *MockIContractTradeRecordRepository) FindOne(executionContext context.Context, id uint) (entities.ContractTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.ContractTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).FindOne), executionContext, id)
}

// FindOpenByOwnerSymbolDirection mocks base method.
func (m *MockIContractTradeRecordRepository) FindOpenByOwnerSymbolDirection(executionContext context.Context, ownerID uint, symbol, direction string) (entities.ContractTradeRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOpenByOwnerSymbolDirection", executionContext, ownerID, symbol, direction)
	ret0, _ := ret[0].(entities.ContractTradeRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindOpenByOwnerSymbolDirection indicates an expected call of FindOpenByOwnerSymbolDirection.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) FindOpenByOwnerSymbolDirection(executionContext, ownerID, symbol, direction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOpenByOwnerSymbolDirection", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).FindOpenByOwnerSymbolDirection), executionContext, ownerID, symbol, direction)
}

// FindPageByOwner mocks base method.
func (m *MockIContractTradeRecordRepository) FindPageByOwner(executionContext context.Context, ownerID uint, filter vo.TradeListFilterVo) ([]entities.ContractTradeRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageByOwner", executionContext, ownerID, filter)
	ret0, _ := ret[0].([]entities.ContractTradeRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPageByOwner indicates an expected call of FindPageByOwner.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) FindPageByOwner(executionContext, ownerID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageByOwner", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).FindPageByOwner), executionContext, ownerID, filter)
}

// MarkDeleted mocks base method.
func (m *MockIContractTradeRecordRepository) MarkDeleted(executionContext context.Context, id uint, deletedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDeleted", executionContext, id, deletedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDeleted indicates an expected call of MarkDeleted.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) MarkDeleted(executionContext, id, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDeleted", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).MarkDeleted), executionContext, id, deletedAt)
}

// Save mocks base method.
func (m *MockIContractTradeRecordRepository) Save(executionContext context.Context, record entities.ContractTradeRecord) (entities.ContractTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, record)
	ret0, _ := ret[0].(entities.ContractTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIContractTradeRecordRepositoryMockRecorder) Save(executionContext, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIContractTradeRecordRepository)(nil).Save), executionContext, record)
}
