// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_order_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_order_proxy.go -destination=mocks/mock_i_contract_order_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractOrderProxy is a mock of IContractOrderProxy interface.
type MockIContractOrderProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIContractOrderProxyMockRecorder
	isgomock struct{}
}

// MockIContractOrderProxyMockRecorder is the mock recorder for MockIContractOrderProxy.
type MockIContractOrderProxyMockRecorder struct {
	mock *MockIContractOrderProxy
}

// NewMockIContractOrderProxy creates a new mock instance.
func NewMockIContractOrderProxy(ctrl *gomock.Controller) *MockIContractOrderProxy {
	mock := &MockIContractOrderProxy{ctrl: ctrl}
	mock.recorder = &MockIContractOrderProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractOrderProxy) EXPECT() *MockIContractOrderProxyMockRecorder {
	return m.recorder
}

// CancelProtectiveOrder mocks base method.
func (m *MockIContractOrderProxy) CancelProtectiveOrder(executionContext context.Context, credential vo.TradingKeyCredentialVo, symbol, clientOrderID string) vo.ContractOrderCallVo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelProtectiveOrder", executionContext, credential, symbol, clientOrderID)
	ret0, _ := ret[0].(vo.ContractOrderCallVo)
	return ret0
}

// CancelProtectiveOrder indicates an expected call of CancelProtectiveOrder.
func (mr *MockIContractOrderProxyMockRecorder) CancelProtectiveOrder(executionContext, credential, symbol, clientOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelProtectiveOrder", reflect.TypeOf((*MockIContractOrderProxy)(nil).CancelProtectiveOrder), executionContext, credential, symbol, clientOrderID)
}

// FindMarketOrder mocks base method.
func (m *MockIContractOrderProxy) FindMarketOrder(executionContext context.Context, credential vo.TradingKeyCredentialVo, symbol, clientOrderID string) (vo.ContractOrderFillVo, vo.ContractOrderCallVo) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMarketOrder", executionContext, credential, symbol, clientOrderID)
	ret0, _ := ret[0].(vo.ContractOrderFillVo)
	ret1, _ := ret[1].(vo.ContractOrderCallVo)
	return ret0, ret1
}

// FindMarketOrder indicates an expected call of FindMarketOrder.
func (mr *MockIContractOrderProxyMockRecorder) FindMarketOrder(executionContext, credential, symbol, clientOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMarketOrder", reflect.TypeOf((*MockIContractOrderProxy)(nil).FindMarketOrder), executionContext, credential, symbol, clientOrderID)
}

// FindProtectiveOrder mocks base method.
func (m *MockIContractOrderProxy) FindProtectiveOrder(executionContext context.Context, credential vo.TradingKeyCredentialVo, symbol, clientOrderID string) vo.ContractOrderCallVo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProtectiveOrder", executionContext, credential, symbol, clientOrderID)
	ret0, _ := ret[0].(vo.ContractOrderCallVo)
	return ret0
}

// FindProtectiveOrder indicates an expected call of FindProtectiveOrder.
func (mr *MockIContractOrderProxyMockRecorder) FindProtectiveOrder(executionContext, credential, symbol, clientOrderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProtectiveOrder", reflect.TypeOf((*MockIContractOrderProxy)(nil).FindProtectiveOrder), executionContext, credential, symbol, clientOrderID)
}

// PlaceMarketOrder mocks base method.
func (m *MockIContractOrderProxy) PlaceMarketOrder(executionContext context.Context, credential vo.TradingKeyCredentialVo, order vo.ContractMarketOrderVo) (vo.ContractOrderFillVo, vo.ContractOrderCallVo) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceMarketOrder", executionContext, credential, order)
	ret0, _ := ret[0].(vo.ContractOrderFillVo)
	ret1, _ := ret[1].(vo.ContractOrderCallVo)
	return ret0, ret1
}

// PlaceMarketOrder indicates an expected call of PlaceMarketOrder.
func (mr *MockIContractOrderProxyMockRecorder) PlaceMarketOrder(executionContext, credential, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceMarketOrder", reflect.TypeOf((*MockIContractOrderProxy)(nil).PlaceMarketOrder), executionContext, credential, order)
}

// PlaceProtectiveOrder mocks base method.
func (m *MockIContractOrderProxy) PlaceProtectiveOrder(executionContext context.Context, credential vo.TradingKeyCredentialVo, order vo.ContractProtectiveOrderVo) vo.ContractOrderCallVo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceProtectiveOrder", executionContext, credential, order)
	ret0, _ := ret[0].(vo.ContractOrderCallVo)
	return ret0
}

// PlaceProtectiveOrder indicates an expected call of PlaceProtectiveOrder.
func (mr *MockIContractOrderProxyMockRecorder) PlaceProtectiveOrder(executionContext, credential, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceProtectiveOrder", reflect.TypeOf((*MockIContractOrderProxy)(nil).PlaceProtectiveOrder), executionContext, credential, order)
}

// PrepareIsolatedLeverage mocks base method.
func (m *MockIContractOrderProxy) PrepareIsolatedLeverage(executionContext context.Context, credential vo.TradingKeyCredentialVo, symbol string, leverage int) vo.ContractOrderCallVo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareIsolatedLeverage", executionContext, credential, symbol, leverage)
	ret0, _ := ret[0].(vo.ContractOrderCallVo)
	return ret0
}

// PrepareIsolatedLeverage indicates an expected call of PrepareIsolatedLeverage.
func (mr *MockIContractOrderProxyMockRecorder) PrepareIsolatedLeverage(executionContext, credential, symbol, leverage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareIsolatedLeverage", reflect.TypeOf((*MockIContractOrderProxy)(nil).PrepareIsolatedLeverage), executionContext, credential, symbol, leverage)
}

// ReadPosition mocks base method.
func (m *MockIContractOrderProxy) ReadPosition(executionContext context.Context, credential vo.TradingKeyCredentialVo, symbol string) (vo.ContractExchangePositionVo, vo.ContractOrderCallVo) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPosition", executionContext, credential, symbol)
	ret0, _ := ret[0].(vo.ContractExchangePositionVo)
	ret1, _ := ret[1].(vo.ContractOrderCallVo)
	return ret0, ret1
}

// ReadPosition indicates an expected call of ReadPosition.
func (mr *MockIContractOrderProxyMockRecorder) ReadPosition(executionContext, credential, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPosition", reflect.TypeOf((*MockIContractOrderProxy)(nil).ReadPosition), executionContext, credential, symbol)
}

// ReadPositionMode mocks base method.
func (m *MockIContractOrderProxy) ReadPositionMode(executionContext context.Context, credential vo.TradingKeyCredentialVo) (bool, vo.ContractOrderCallVo) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPositionMode", executionContext, credential)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(vo.ContractOrderCallVo)
	return ret0, ret1
}

// ReadPositionMode indicates an expected call of ReadPositionMode.
func (mr *MockIContractOrderProxyMockRecorder) ReadPositionMode(executionContext, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPositionMode", reflect.TypeOf((*MockIContractOrderProxy)(nil).ReadPositionMode), executionContext, credential)
}
