// Code generated by MockGen. DO NOT EDIT.
// Source: i_assistant_created_subject_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_assistant_created_subject_repository.go -destination=mocks/mock_i_assistant_created_subject_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIAssistantCreatedSubjectRepository is a mock of IAssistantCreatedSubjectRepository interface.
type MockIAssistantCreatedSubjectRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAssistantCreatedSubjectRepositoryMockRecorder
	isgomock struct{}
}

// MockIAssistantCreatedSubjectRepositoryMockRecorder is the mock recorder for MockIAssistantCreatedSubjectRepository.
type MockIAssistantCreatedSubjectRepositoryMockRecorder struct {
	mock *MockIAssistantCreatedSubjectRepository
}

// NewMockIAssistantCreatedSubjectRepository creates a new mock instance.
func NewMockIAssistantCreatedSubjectRepository(ctrl *gomock.Controller) *MockIAssistantCreatedSubjectRepository {
	mock := &MockIAssistantCreatedSubjectRepository{ctrl: ctrl}
	mock.recorder = &MockIAssistantCreatedSubjectRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssistantCreatedSubjectRepository) EXPECT() *MockIAssistantCreatedSubjectRepositoryMockRecorder {
	return m.recorder
}

// Exists mocks base method.
func (m *MockIAssistantCreatedSubjectRepository) Exists(executionContext context.Context, conversationID uint, subjectKind string, subjectID uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", executionContext, conversationID, subjectKind, subjectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockIAssistantCreatedSubjectRepositoryMockRecorder) Exists(executionContext, conversationID, subjectKind, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockIAssistantCreatedSubjectRepository)(nil).Exists), executionContext, conversationID, subjectKind, subjectID)
}

// Save mocks base method.
func (m *MockIAssistantCreatedSubjectRepository) Save(executionContext context.Context, assistantCreatedSubject entities.AssistantCreatedSubject) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, assistantCreatedSubject)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockIAssistantCreatedSubjectRepositoryMockRecorder) Save(executionContext, assistantCreatedSubject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIAssistantCreatedSubjectRepository)(nil).Save), executionContext, assistantCreatedSubject)
}
