// Code generated by MockGen. DO NOT EDIT.
// Source: i_trade_journal_setting_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_trade_journal_setting_repository.go -destination=mocks/mock_i_trade_journal_setting_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockITradeJournalSettingRepository is a mock of ITradeJournalSettingRepository interface.
type MockITradeJournalSettingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockITradeJournalSettingRepositoryMockRecorder
	isgomock struct{}
}

// MockITradeJournalSettingRepositoryMockRecorder is the mock recorder for MockITradeJournalSettingRepository.
type MockITradeJournalSettingRepositoryMockRecorder struct {
	mock *MockITradeJournalSettingRepository
}

// NewMockITradeJournalSettingRepository creates a new mock instance.
func NewMockITradeJournalSettingRepository(ctrl *gomock.Controller) *MockITradeJournalSettingRepository {
	mock := &MockITradeJournalSettingRepository{ctrl: ctrl}
	mock.recorder = &MockITradeJournalSettingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITradeJournalSettingRepository) EXPECT() *MockITradeJournalSettingRepositoryMockRecorder {
	return m.recorder
}

// FindOneByUser mocks base method.
func (m *MockITradeJournalSettingRepository) FindOneByUser(executionContext context.Context, userID uint) (entities.TradeJournalSetting, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUser", executionContext, userID)
	ret0, _ := ret[0].(entities.TradeJournalSetting)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindOneByUser indicates an expected call of FindOneByUser.
func (mr *MockITradeJournalSettingRepositoryMockRecorder) FindOneByUser(executionContext, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUser", reflect.TypeOf((*MockITradeJournalSettingRepository)(nil).FindOneByUser), executionContext, userID)
}

// MarkDefaultMistakeTagsSeeded mocks base method.
func (m *MockITradeJournalSettingRepository) MarkDefaultMistakeTagsSeeded(executionContext context.Context, userID uint, seededAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDefaultMistakeTagsSeeded", executionContext, userID, seededAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDefaultMistakeTagsSeeded indicates an expected call of MarkDefaultMistakeTagsSeeded.
func (mr *MockITradeJournalSettingRepositoryMockRecorder) MarkDefaultMistakeTagsSeeded(executionContext, userID, seededAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDefaultMistakeTagsSeeded", reflect.TypeOf((*MockITradeJournalSettingRepository)(nil).MarkDefaultMistakeTagsSeeded), executionContext, userID, seededAt)
}

// SaveFeeRates mocks base method.
func (m *MockITradeJournalSettingRepository) SaveFeeRates(executionContext context.Context, setting entities.TradeJournalSetting) (entities.TradeJournalSetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFeeRates", executionContext, setting)
	ret0, _ := ret[0].(entities.TradeJournalSetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveFeeRates indicates an expected call of SaveFeeRates.
func (mr *MockITradeJournalSettingRepositoryMockRecorder) SaveFeeRates(executionContext, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFeeRates", reflect.TypeOf((*MockITradeJournalSettingRepository)(nil).SaveFeeRates), executionContext, setting)
}
