// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_funding_rate_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_funding_rate_proxy.go -destination=mocks/mock_i_contract_funding_rate_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractFundingRateProxy is a mock of IContractFundingRateProxy interface.
type MockIContractFundingRateProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIContractFundingRateProxyMockRecorder
	isgomock struct{}
}

// MockIContractFundingRateProxyMockRecorder is the mock recorder for MockIContractFundingRateProxy.
type MockIContractFundingRateProxyMockRecorder struct {
	mock *MockIContractFundingRateProxy
}

// NewMockIContractFundingRateProxy creates a new mock instance.
func NewMockIContractFundingRateProxy(ctrl *gomock.Controller) *MockIContractFundingRateProxy {
	mock := &MockIContractFundingRateProxy{ctrl: ctrl}
	mock.recorder = &MockIContractFundingRateProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractFundingRateProxy) EXPECT() *MockIContractFundingRateProxyMockRecorder {
	return m.recorder
}

// FetchFundingRateSettlements mocks base method.
func (m *MockIContractFundingRateProxy) FetchFundingRateSettlements(executionContext context.Context, symbol string, after time.Time) ([]vo.ContractFundingRateSettlementVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFundingRateSettlements", executionContext, symbol, after)
	ret0, _ := ret[0].([]vo.ContractFundingRateSettlementVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFundingRateSettlements indicates an expected call of FetchFundingRateSettlements.
func (mr *MockIContractFundingRateProxyMockRecorder) FetchFundingRateSettlements(executionContext, symbol, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFundingRateSettlements", reflect.TypeOf((*MockIContractFundingRateProxy)(nil).FetchFundingRateSettlements), executionContext, symbol, after)
}
