// Code generated by MockGen. DO NOT EDIT.
// Source: i_conversation_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_conversation_repository.go -destination=mocks/mock_i_conversation_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIConversationRepository is a mock of IConversationRepository interface.
type MockIConversationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIConversationRepositoryMockRecorder
	isgomock struct{}
}

// MockIConversationRepositoryMockRecorder is the mock recorder for MockIConversationRepository.
type MockIConversationRepositoryMockRecorder struct {
	mock *MockIConversationRepository
}

// NewMockIConversationRepository creates a new mock instance.
func NewMockIConversationRepository(ctrl *gomock.Controller) *MockIConversationRepository {
	mock := &MockIConversationRepository{ctrl: ctrl}
	mock.recorder = &MockIConversationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConversationRepository) EXPECT() *MockIConversationRepositoryMockRecorder {
	return m.recorder
}

// AppendTurn mocks base method.
func (m *MockIConversationRepository) AppendTurn(executionContext context.Context, conversationId uint, turn entities.AssistantTurn) (entities.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendTurn", executionContext, conversationId, turn)
	ret0, _ := ret[0].(entities.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendTurn indicates an expected call of AppendTurn.
func (mr *MockIConversationRepositoryMockRecorder) AppendTurn(executionContext, conversationId, turn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendTurn", reflect.TypeOf((*MockIConversationRepository)(nil).AppendTurn), executionContext, conversationId, turn)
}

// FindAll mocks base method.
func (m *MockIConversationRepository) FindAll(executionContext context.Context) ([]entities.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", executionContext)
	ret0, _ := ret[0].([]entities.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIConversationRepositoryMockRecorder) FindAll(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIConversationRepository)(nil).FindAll), executionContext)
}

// FindOne mocks base method.
func (m *MockIConversationRepository) FindOne(executionContext context.Context, id uint) (entities.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIConversationRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIConversationRepository)(nil).FindOne), executionContext, id)
}

// Save mocks base method.
func (m *MockIConversationRepository) Save(executionContext context.Context, conversation entities.Conversation) (entities.Conversation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, conversation)
	ret0, _ := ret[0].(entities.Conversation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIConversationRepositoryMockRecorder) Save(executionContext, conversation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIConversationRepository)(nil).Save), executionContext, conversation)
}

// SumUsageBetween mocks base method.
func (m *MockIConversationRepository) SumUsageBetween(executionContext context.Context, from, to time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SumUsageBetween", executionContext, from, to)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SumUsageBetween indicates an expected call of SumUsageBetween.
func (mr *MockIConversationRepositoryMockRecorder) SumUsageBetween(executionContext, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SumUsageBetween", reflect.TypeOf((*MockIConversationRepository)(nil).SumUsageBetween), executionContext, from, to)
}
