// Code generated by MockGen. DO NOT EDIT.
// Source: i_job_leadership_lease_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_job_leadership_lease_repository.go -destination=mocks/mock_i_job_leadership_lease_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockIJobLeadershipLeaseRepository is a mock of IJobLeadershipLeaseRepository interface.
type MockIJobLeadershipLeaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIJobLeadershipLeaseRepositoryMockRecorder
	isgomock struct{}
}

// MockIJobLeadershipLeaseRepositoryMockRecorder is the mock recorder for MockIJobLeadershipLeaseRepository.
type MockIJobLeadershipLeaseRepositoryMockRecorder struct {
	mock *MockIJobLeadershipLeaseRepository
}

// NewMockIJobLeadershipLeaseRepository creates a new mock instance.
func NewMockIJobLeadershipLeaseRepository(ctrl *gomock.Controller) *MockIJobLeadershipLeaseRepository {
	mock := &MockIJobLeadershipLeaseRepository{ctrl: ctrl}
	mock.recorder = &MockIJobLeadershipLeaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJobLeadershipLeaseRepository) EXPECT() *MockIJobLeadershipLeaseRepositoryMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockIJobLeadershipLeaseRepository) Acquire(executionContext context.Context, name, holderName string, now, expiresAt time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", executionContext, name, holderName, now, expiresAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockIJobLeadershipLeaseRepositoryMockRecorder) Acquire(executionContext, name, holderName, now, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockIJobLeadershipLeaseRepository)(nil).Acquire), executionContext, name, holderName, now, expiresAt)
}

// Release mocks base method.
func (m *MockIJobLeadershipLeaseRepository) Release(executionContext context.Context, name, holderName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", executionContext, name, holderName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockIJobLeadershipLeaseRepositoryMockRecorder) Release(executionContext, name, holderName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockIJobLeadershipLeaseRepository)(nil).Release), executionContext, name, holderName)
}
