// Code generated by MockGen. DO NOT EDIT.
// Source: i_spot_trade_record_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_spot_trade_record_repository.go -destination=mocks/mock_i_spot_trade_record_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockISpotTradeRecordRepository is a mock of ISpotTradeRecordRepository interface.
type MockISpotTradeRecordRepository struct {
	ctrl     *gomock.Controller
	recorder *MockISpotTradeRecordRepositoryMockRecorder
	isgomock struct{}
}

// MockISpotTradeRecordRepositoryMockRecorder is the mock recorder for MockISpotTradeRecordRepository.
type MockISpotTradeRecordRepositoryMockRecorder struct {
	mock *MockISpotTradeRecordRepository
}

// NewMockISpotTradeRecordRepository creates a new mock instance.
func NewMockISpotTradeRecordRepository(ctrl *gomock.Controller) *MockISpotTradeRecordRepository {
	mock := &MockISpotTradeRecordRepository{ctrl: ctrl}
	mock.recorder = &MockISpotTradeRecordRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISpotTradeRecordRepository) EXPECT() *MockISpotTradeRecordRepositoryMockRecorder {
	return m.recorder
}

// CountByTag mocks base method.
func (m *MockISpotTradeRecordRepository) CountByTag(executionContext context.Context, tagID uint) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByTag", executionContext, tagID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByTag indicates an expected call of CountByTag.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) CountByTag(executionContext, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByTag", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).CountByTag), executionContext, tagID)
}

// Create mocks base method.
func (m *MockISpotTradeRecordRepository) Create(executionContext context.Context, record entities.SpotTradeRecord) (entities.SpotTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", executionContext, record)
	ret0, _ := ret[0].(entities.SpotTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) Create(executionContext, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).Create), executionContext, record)
}

// FindClosedByOwner mocks base method.
func (m *MockISpotTradeRecordRepository) FindClosedByOwner(executionContext context.Context, ownerID uint, closedSince *time.Time) ([]entities.SpotTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindClosedByOwner", executionContext, ownerID, closedSince)
	ret0, _ := ret[0].([]entities.SpotTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindClosedByOwner indicates an expected call of FindClosedByOwner.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) FindClosedByOwner(executionContext, ownerID, closedSince any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindClosedByOwner", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).FindClosedByOwner), executionContext, ownerID, closedSince)
}

// FindClosedByOwnerAndTradingStrategy mocks base method.
func (m *MockISpotTradeRecordRepository) FindClosedByOwnerAndTradingStrategy(executionContext context.Context, ownerID, tradingStrategyID uint) ([]entities.SpotTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindClosedByOwnerAndTradingStrategy", executionContext, ownerID, tradingStrategyID)
	ret0, _ := ret[0].([]entities.SpotTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindClosedByOwnerAndTradingStrategy indicates an expected call of FindClosedByOwnerAndTradingStrategy.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) FindClosedByOwnerAndTradingStrategy(executionContext, ownerID, tradingStrategyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindClosedByOwnerAndTradingStrategy", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).FindClosedByOwnerAndTradingStrategy), executionContext, ownerID, tradingStrategyID)
}

// FindOne mocks base method.
func (m *MockISpotTradeRecordRepository) FindOne(executionContext context.Context, id uint) (entities.SpotTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.SpotTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).FindOne), executionContext, id)
}

// FindOpenByOwnerSymbol mocks base method.
func (m *MockISpotTradeRecordRepository) FindOpenByOwnerSymbol(executionContext context.Context, ownerID uint, symbol string) (entities.SpotTradeRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOpenByOwnerSymbol", executionContext, ownerID, symbol)
	ret0, _ := ret[0].(entities.SpotTradeRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindOpenByOwnerSymbol indicates an expected call of FindOpenByOwnerSymbol.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) FindOpenByOwnerSymbol(executionContext, ownerID, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOpenByOwnerSymbol", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).FindOpenByOwnerSymbol), executionContext, ownerID, symbol)
}

// FindPageByOwner mocks base method.
func (m *MockISpotTradeRecordRepository) FindPageByOwner(executionContext context.Context, ownerID uint, filter vo.TradeListFilterVo) ([]entities.SpotTradeRecord, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPageByOwner", executionContext, ownerID, filter)
	ret0, _ := ret[0].([]entities.SpotTradeRecord)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindPageByOwner indicates an expected call of FindPageByOwner.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) FindPageByOwner(executionContext, ownerID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPageByOwner", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).FindPageByOwner), executionContext, ownerID, filter)
}

// MarkDeleted mocks base method.
func (m *MockISpotTradeRecordRepository) MarkDeleted(executionContext context.Context, id uint, deletedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDeleted", executionContext, id, deletedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDeleted indicates an expected call of MarkDeleted.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) MarkDeleted(executionContext, id, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDeleted", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).MarkDeleted), executionContext, id, deletedAt)
}

// Save mocks base method.
func (m *MockISpotTradeRecordRepository) Save(executionContext context.Context, record entities.SpotTradeRecord) (entities.SpotTradeRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, record)
	ret0, _ := ret[0].(entities.SpotTradeRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockISpotTradeRecordRepositoryMockRecorder) Save(executionContext, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockISpotTradeRecordRepository)(nil).Save), executionContext, record)
}
