// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_maintenance_margin_tier_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_maintenance_margin_tier_proxy.go -destination=mocks/mock_i_contract_maintenance_margin_tier_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractMaintenanceMarginTierProxy is a mock of IContractMaintenanceMarginTierProxy interface.
type MockIContractMaintenanceMarginTierProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIContractMaintenanceMarginTierProxyMockRecorder
	isgomock struct{}
}

// MockIContractMaintenanceMarginTierProxyMockRecorder is the mock recorder for MockIContractMaintenanceMarginTierProxy.
type MockIContractMaintenanceMarginTierProxyMockRecorder struct {
	mock *MockIContractMaintenanceMarginTierProxy
}

// NewMockIContractMaintenanceMarginTierProxy creates a new mock instance.
func NewMockIContractMaintenanceMarginTierProxy(ctrl *gomock.Controller) *MockIContractMaintenanceMarginTierProxy {
	mock := &MockIContractMaintenanceMarginTierProxy{ctrl: ctrl}
	mock.recorder = &MockIContractMaintenanceMarginTierProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractMaintenanceMarginTierProxy) EXPECT() *MockIContractMaintenanceMarginTierProxyMockRecorder {
	return m.recorder
}

// FetchMaintenanceMarginLadders mocks base method.
func (m *MockIContractMaintenanceMarginTierProxy) FetchMaintenanceMarginLadders(executionContext context.Context) ([]vo.ContractMaintenanceMarginLadderVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMaintenanceMarginLadders", executionContext)
	ret0, _ := ret[0].([]vo.ContractMaintenanceMarginLadderVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMaintenanceMarginLadders indicates an expected call of FetchMaintenanceMarginLadders.
func (mr *MockIContractMaintenanceMarginTierProxyMockRecorder) FetchMaintenanceMarginLadders(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMaintenanceMarginLadders", reflect.TypeOf((*MockIContractMaintenanceMarginTierProxy)(nil).FetchMaintenanceMarginLadders), executionContext)
}
