// Code generated by MockGen. DO NOT EDIT.
// Source: i_assistant_pending_revision_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_assistant_pending_revision_repository.go -destination=mocks/mock_i_assistant_pending_revision_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIAssistantPendingRevisionRepository is a mock of IAssistantPendingRevisionRepository interface.
type MockIAssistantPendingRevisionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAssistantPendingRevisionRepositoryMockRecorder
	isgomock struct{}
}

// MockIAssistantPendingRevisionRepositoryMockRecorder is the mock recorder for MockIAssistantPendingRevisionRepository.
type MockIAssistantPendingRevisionRepositoryMockRecorder struct {
	mock *MockIAssistantPendingRevisionRepository
}

// NewMockIAssistantPendingRevisionRepository creates a new mock instance.
func NewMockIAssistantPendingRevisionRepository(ctrl *gomock.Controller) *MockIAssistantPendingRevisionRepository {
	mock := &MockIAssistantPendingRevisionRepository{ctrl: ctrl}
	mock.recorder = &MockIAssistantPendingRevisionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAssistantPendingRevisionRepository) EXPECT() *MockIAssistantPendingRevisionRepositoryMockRecorder {
	return m.recorder
}

// FindOne mocks base method.
func (m *MockIAssistantPendingRevisionRepository) FindOne(executionContext context.Context, id uint) (entities.AssistantPendingRevision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", executionContext, id)
	ret0, _ := ret[0].(entities.AssistantPendingRevision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIAssistantPendingRevisionRepositoryMockRecorder) FindOne(executionContext, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIAssistantPendingRevisionRepository)(nil).FindOne), executionContext, id)
}

// Save mocks base method.
func (m *MockIAssistantPendingRevisionRepository) Save(executionContext context.Context, assistantPendingRevision entities.AssistantPendingRevision) (entities.AssistantPendingRevision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", executionContext, assistantPendingRevision)
	ret0, _ := ret[0].(entities.AssistantPendingRevision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIAssistantPendingRevisionRepositoryMockRecorder) Save(executionContext, assistantPendingRevision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIAssistantPendingRevisionRepository)(nil).Save), executionContext, assistantPendingRevision)
}

// TransitionStatus mocks base method.
func (m *MockIAssistantPendingRevisionRepository) TransitionStatus(executionContext context.Context, id uint, from, to string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionStatus", executionContext, id, from, to)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionStatus indicates an expected call of TransitionStatus.
func (mr *MockIAssistantPendingRevisionRepositoryMockRecorder) TransitionStatus(executionContext, id, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionStatus", reflect.TypeOf((*MockIAssistantPendingRevisionRepository)(nil).TransitionStatus), executionContext, id, from, to)
}
