// Code generated by MockGen. DO NOT EDIT.
// Source: i_contract_position_statistic_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_contract_position_statistic_repository.go -destination=mocks/mock_i_contract_position_statistic_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domains "github.com/CodeMachine0121/go-trading/internal/domain/models/domains"
	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIContractPositionStatisticRepository is a mock of IContractPositionStatisticRepository interface.
type MockIContractPositionStatisticRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContractPositionStatisticRepositoryMockRecorder
	isgomock struct{}
}

// MockIContractPositionStatisticRepositoryMockRecorder is the mock recorder for MockIContractPositionStatisticRepository.
type MockIContractPositionStatisticRepositoryMockRecorder struct {
	mock *MockIContractPositionStatisticRepository
}

// NewMockIContractPositionStatisticRepository creates a new mock instance.
func NewMockIContractPositionStatisticRepository(ctrl *gomock.Controller) *MockIContractPositionStatisticRepository {
	mock := &MockIContractPositionStatisticRepository{ctrl: ctrl}
	mock.recorder = &MockIContractPositionStatisticRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractPositionStatisticRepository) EXPECT() *MockIContractPositionStatisticRepositoryMockRecorder {
	return m.recorder
}

// CountInRange mocks base method.
func (m *MockIContractPositionStatisticRepository) CountInRange(executionContext context.Context, symbol string, startTime, endTime time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountInRange", executionContext, symbol, startTime, endTime)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountInRange indicates an expected call of CountInRange.
func (mr *MockIContractPositionStatisticRepositoryMockRecorder) CountInRange(executionContext, symbol, startTime, endTime any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountInRange", reflect.TypeOf((*MockIContractPositionStatisticRepository)(nil).CountInRange), executionContext, symbol, startTime, endTime)
}

// FindInRange mocks base method.
func (m *MockIContractPositionStatisticRepository) FindInRange(executionContext context.Context, query domains.KCandleQueryDomain, limit int) ([]entities.ContractPositionStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindInRange", executionContext, query, limit)
	ret0, _ := ret[0].([]entities.ContractPositionStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindInRange indicates an expected call of FindInRange.
func (mr *MockIContractPositionStatisticRepositoryMockRecorder) FindInRange(executionContext, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindInRange", reflect.TypeOf((*MockIContractPositionStatisticRepository)(nil).FindInRange), executionContext, query, limit)
}

// FindLatest mocks base method.
func (m *MockIContractPositionStatisticRepository) FindLatest(executionContext context.Context, symbol string) (entities.ContractPositionStatistic, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatest", executionContext, symbol)
	ret0, _ := ret[0].(entities.ContractPositionStatistic)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindLatest indicates an expected call of FindLatest.
func (mr *MockIContractPositionStatisticRepositoryMockRecorder) FindLatest(executionContext, symbol any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatest", reflect.TypeOf((*MockIContractPositionStatisticRepository)(nil).FindLatest), executionContext, symbol)
}

// SaveAllIfAbsent mocks base method.
func (m *MockIContractPositionStatisticRepository) SaveAllIfAbsent(executionContext context.Context, statistics []entities.ContractPositionStatistic) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAllIfAbsent", executionContext, statistics)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAllIfAbsent indicates an expected call of SaveAllIfAbsent.
func (mr *MockIContractPositionStatisticRepositoryMockRecorder) SaveAllIfAbsent(executionContext, statistics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAllIfAbsent", reflect.TypeOf((*MockIContractPositionStatisticRepository)(nil).SaveAllIfAbsent), executionContext, statistics)
}
