// Code generated by MockGen. DO NOT EDIT.
// Source: i_access_token_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_access_token_proxy.go -destination=mocks/mock_i_access_token_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockIAccessTokenProxy is a mock of IAccessTokenProxy interface.
type MockIAccessTokenProxy struct {
	ctrl     *gomock.Controller
	recorder *MockIAccessTokenProxyMockRecorder
	isgomock struct{}
}

// MockIAccessTokenProxyMockRecorder is the mock recorder for MockIAccessTokenProxy.
type MockIAccessTokenProxyMockRecorder struct {
	mock *MockIAccessTokenProxy
}

// NewMockIAccessTokenProxy creates a new mock instance.
func NewMockIAccessTokenProxy(ctrl *gomock.Controller) *MockIAccessTokenProxy {
	mock := &MockIAccessTokenProxy{ctrl: ctrl}
	mock.recorder = &MockIAccessTokenProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAccessTokenProxy) EXPECT() *MockIAccessTokenProxyMockRecorder {
	return m.recorder
}

// Issue mocks base method.
func (m *MockIAccessTokenProxy) Issue(userID uint, expiresAt time.Time) (vo.AccessTokenVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Issue", userID, expiresAt)
	ret0, _ := ret[0].(vo.AccessTokenVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Issue indicates an expected call of Issue.
func (mr *MockIAccessTokenProxyMockRecorder) Issue(userID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Issue", reflect.TypeOf((*MockIAccessTokenProxy)(nil).Issue), userID, expiresAt)
}

// UserIdentifiedBy mocks base method.
func (m *MockIAccessTokenProxy) UserIdentifiedBy(accessToken string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserIdentifiedBy", accessToken)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserIdentifiedBy indicates an expected call of UserIdentifiedBy.
func (mr *MockIAccessTokenProxyMockRecorder) UserIdentifiedBy(accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserIdentifiedBy", reflect.TypeOf((*MockIAccessTokenProxy)(nil).UserIdentifiedBy), accessToken)
}
