// Code generated by MockGen. DO NOT EDIT.
// Source: i_trading_key_verification_proxy.go
//
// Generated by this command:
//
//	mockgen -source=i_trading_key_verification_proxy.go -destination=mocks/mock_i_trading_key_verification_proxy.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vo "github.com/CodeMachine0121/go-trading/internal/domain/models/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockITradingKeyVerificationProxy is a mock of ITradingKeyVerificationProxy interface.
type MockITradingKeyVerificationProxy struct {
	ctrl     *gomock.Controller
	recorder *MockITradingKeyVerificationProxyMockRecorder
	isgomock struct{}
}

// MockITradingKeyVerificationProxyMockRecorder is the mock recorder for MockITradingKeyVerificationProxy.
type MockITradingKeyVerificationProxyMockRecorder struct {
	mock *MockITradingKeyVerificationProxy
}

// NewMockITradingKeyVerificationProxy creates a new mock instance.
func NewMockITradingKeyVerificationProxy(ctrl *gomock.Controller) *MockITradingKeyVerificationProxy {
	mock := &MockITradingKeyVerificationProxy{ctrl: ctrl}
	mock.recorder = &MockITradingKeyVerificationProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITradingKeyVerificationProxy) EXPECT() *MockITradingKeyVerificationProxyMockRecorder {
	return m.recorder
}

// VerifyTradingKey mocks base method.
func (m *MockITradingKeyVerificationProxy) VerifyTradingKey(executionContext context.Context, credential vo.TradingKeyCredentialVo) (vo.TradingKeyVerificationVo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyTradingKey", executionContext, credential)
	ret0, _ := ret[0].(vo.TradingKeyVerificationVo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyTradingKey indicates an expected call of VerifyTradingKey.
func (mr *MockITradingKeyVerificationProxyMockRecorder) VerifyTradingKey(executionContext, credential any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyTradingKey", reflect.TypeOf((*MockITradingKeyVerificationProxy)(nil).VerifyTradingKey), executionContext, credential)
}
