// Code generated by MockGen. DO NOT EDIT.
// Source: i_strategy_repository.go
//
// Generated by this command:
//
//	mockgen -source=i_strategy_repository.go -destination=mocks/mock_i_strategy_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entities "github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockIStrategyRepository is a mock of IStrategyRepository interface.
type MockIStrategyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIStrategyRepositoryMockRecorder
	isgomock struct{}
}

// MockIStrategyRepositoryMockRecorder is the mock recorder for MockIStrategyRepository.
type MockIStrategyRepositoryMockRecorder struct {
	mock *MockIStrategyRepository
}

// NewMockIStrategyRepository creates a new mock instance.
func NewMockIStrategyRepository(ctrl *gomock.Controller) *MockIStrategyRepository {
	mock := &MockIStrategyRepository{ctrl: ctrl}
	mock.recorder = &MockIStrategyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStrategyRepository) EXPECT() *MockIStrategyRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockIStrategyRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIStrategyRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIStrategyRepository)(nil).Delete), id)
}

// FindAll mocks base method.
func (m *MockIStrategyRepository) FindAll() ([]entities.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]entities.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockIStrategyRepositoryMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockIStrategyRepository)(nil).FindAll))
}

// FindOne mocks base method.
func (m *MockIStrategyRepository) FindOne(id uint) (entities.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", id)
	ret0, _ := ret[0].(entities.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockIStrategyRepositoryMockRecorder) FindOne(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockIStrategyRepository)(nil).FindOne), id)
}

// Save mocks base method.
func (m *MockIStrategyRepository) Save(strategy entities.Strategy) (entities.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", strategy)
	ret0, _ := ret[0].(entities.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIStrategyRepositoryMockRecorder) Save(strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIStrategyRepository)(nil).Save), strategy)
}

// Update mocks base method.
func (m *MockIStrategyRepository) Update(strategy entities.Strategy) (entities.Strategy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", strategy)
	ret0, _ := ret[0].(entities.Strategy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIStrategyRepositoryMockRecorder) Update(strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIStrategyRepository)(nil).Update), strategy)
}
