// Code generated by MockGen. DO NOT EDIT.
// Source: i_background_job.go
//
// Generated by this command:
//
//	mockgen -source=i_background_job.go -destination=mocks/mock_i_background_job.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIBackgroundJob is a mock of IBackgroundJob interface.
type MockIBackgroundJob struct {
	ctrl     *gomock.Controller
	recorder *MockIBackgroundJobMockRecorder
	isgomock struct{}
}

// MockIBackgroundJobMockRecorder is the mock recorder for MockIBackgroundJob.
type MockIBackgroundJobMockRecorder struct {
	mock *MockIBackgroundJob
}

// NewMockIBackgroundJob creates a new mock instance.
func NewMockIBackgroundJob(ctrl *gomock.Controller) *MockIBackgroundJob {
	mock := &MockIBackgroundJob{ctrl: ctrl}
	mock.recorder = &MockIBackgroundJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBackgroundJob) EXPECT() *MockIBackgroundJobMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockIBackgroundJob) Start(executionContext context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", executionContext)
}

// Start indicates an expected call of Start.
func (mr *MockIBackgroundJobMockRecorder) Start(executionContext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIBackgroundJob)(nil).Start), executionContext)
}

// Stop mocks base method.
func (m *MockIBackgroundJob) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockIBackgroundJobMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockIBackgroundJob)(nil).Stop))
}
