package persistence

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/CodeMachine0121/go-trading/internal/domain/models/domains"
	"github.com/CodeMachine0121/go-trading/internal/domain/models/entities"
	"github.com/jackc/pgx/v5/pgconn"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// foreignKeyViolationCode is what PostgreSQL calls a broken foreign key.
//
// An adoption has exactly one foreign key — the publication it hangs from — so this
// code alone says what went wrong without also having to name the constraint. That
// is deliberate: a constraint name is generated by the ORM and repeating it here
// would be a second spelling that can drift, and when it drifted, adopting
// something unpublished would stop reading as "not found" and start reading as a
// storage failure. The single-foreign-key fact is asserted by a schema test rather
// than assumed.
const foreignKeyViolationCode = "23503"

// StrategyAdoptionRepository records which published strategies each person keeps.
type StrategyAdoptionRepository struct {
	database *gorm.DB
}

func NewStrategyAdoptionRepository(database *gorm.DB) *StrategyAdoptionRepository {
	return &StrategyAdoptionRepository{database: database}
}

// Adopt puts this published strategy on this person's shelf, or leaves it where it
// already is. Taking one twice is one row for the same reason publishing twice is:
// the conflict is settled by the index, not by looking first.
//
// A strategy that is not on the marketplace has no publication for this row to hang
// from, so the write breaks the foreign key — and that is reported as the one
// sentence a closed door gives, never as "that exists but is not shared".
func (strategyAdoptionRepository *StrategyAdoptionRepository) Adopt(
	executionContext context.Context, userID uint, strategyID uint, adoptedAt time.Time,
) error {
	adoption := entities.StrategyAdoption{UserID: userID, StrategyID: strategyID, AdoptedAt: adoptedAt.UTC()}

	result := strategyAdoptionRepository.database.WithContext(executionContext).
		Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "user_id"}, {Name: "strategy_id"}},
			DoNothing: true,
		}).
		Create(&adoption)
	if strategyAdoptionRepository.isNotOnTheMarketplace(result.Error) {
		return domains.StrategyNotFound(strategyID)
	}
	if result.Error != nil {
		return fmt.Errorf("adopt strategy: %w", result.Error)
	}

	return nil
}

// Abandon takes it off their shelf. Doing so to something they never took affects
// no rows and is not a failure.
func (strategyAdoptionRepository *StrategyAdoptionRepository) Abandon(
	executionContext context.Context, userID uint, strategyID uint,
) error {
	result := strategyAdoptionRepository.database.WithContext(executionContext).
		Where(clause.Eq{Column: "user_id", Value: userID}).
		Where(clause.Eq{Column: "strategy_id", Value: strategyID}).
		Delete(&entities.StrategyAdoption{})
	if result.Error != nil {
		return fmt.Errorf("abandon strategy: %w", result.Error)
	}

	return nil
}

// isNotOnTheMarketplace says whether this write failed because there is no
// publication to hang the adoption from — the table's only foreign key, so a broken
// one can mean nothing else. Every other kind of storage failure stays a storage
// failure: answering "not found" for a clash the marketplace had no part in would
// send whoever reads it looking for a strategy that is sitting right there.
func (strategyAdoptionRepository *StrategyAdoptionRepository) isNotOnTheMarketplace(writeError error) bool {
	postgresError, isPostgresError := errors.AsType[*pgconn.PgError](writeError)
	if !isPostgresError {
		return false
	}

	return postgresError.Code == foreignKeyViolationCode
}
